// Interface strings only. These are chrome: navigation, buttons, labels.
//
// Every value in this table must be JSON serialisable. The whole object is
// handed to client components such as the consent banner and the plan panel,
// and React refuses to send a function across that boundary. A function here
// fails the build at prerender time, which is exactly what happened once.
// Use {placeholder} tokens and interpolate at the call site instead.
// Editorial copy never lives here, because editorial copy is written per market
// and not translated.

const EN = {
  selectPlan: 'Select this plan',
  continueToCheckout: 'Continue to checkout',
  backToPlans: 'Back to plans',
  planDetailTitle: 'Plan details',
  planSlotTitle: 'Plan slot',
  planSlotAria: 'Plan fields, values arrive when a supplier is connected',
  planSlotNote: 'These are the fields every plan will carry. We leave them empty rather than fill them with numbers we cannot honour yet.',
  valueNotSet: 'not set yet',
  planFields: { data: 'Data', validity: 'Validity', hotspot: 'Hotspot', network: 'Networks', price: 'Price' },
  checkoutUnavailableTitle: 'This plan is not available for instant activation yet',
  checkoutUnavailableBody: 'No supplier is connected, so there is nothing to activate and nothing to charge you for. Tell us where you are going and you will be first to know when this destination goes live.',
  checkoutNoPaymentNote: 'No payment is taken on this site. Nothing you clicked has cost you anything.',
  filterAll: 'All destinations',
  filterRegion: 'Filter by region',
  emptyResults: 'Nothing matches that filter yet',
  regionDestinationsHeading: 'All {count} destinations in {name}',
  brand: 'Livdar',
  product: 'eSIM',
  skipToContent: 'Skip to content',
  nav: { esim: 'Destinations', regions: 'Regions', guides: 'Guides', compare: 'Compare', compatibility: 'Compatibility' },
  searchLabel: 'Where are you going?',
  searchPlaceholder: 'Search a country or region',
  searchHint: 'Start typing a destination',
  searchEmpty: 'No destination matches that yet',
  searchOpen: 'Open search',
  viewPlans: 'View plans',
  checkAvailability: 'Check availability',
  notifyMe: 'Notify me when plans go live',
  compareOptions: 'Compare options',
  seeConnectivity: 'See connectivity options',
  popularDestinations: 'Popular destinations',
  allDestinations: 'All destinations',
  regionalPlans: 'Regional plans',
  howItWorks: 'How it works',
  faq: 'Common questions',
  relatedDestinations: 'Nearby destinations',
  networksLabel: 'Networks in the country',
  callingCode: 'Dialling code',
  regionLabel: 'Region',
  languageLabel: 'Language',
  languageSwitch: 'Change language',
  backToHub: 'All eSIM destinations',
  notConnectedTitle: 'Plans are not on sale yet',
  notConnectedBody: 'We are testing which destinations people actually need before we connect a supplier. Tell us where you are going and you will be first to know when plans for that destination go live.',
  destinationsCount: 'destinations',
  languagesCount: 'languages',
  footerLegal: 'Legal',
  footerProduct: 'Product',
  footerCompany: 'Company',
  privacy: 'Privacy',
  cookies: 'Cookies',
  terms: 'Terms',
  contact: 'Contact',
  about: 'About Livdar',
  consentTitle: 'Your choice on cookies',
  consentBody: 'We use cookies that are needed for the site to work. Statistics and marketing cookies only run if you allow them.',
  consentAccept: 'Accept all',
  consentReject: 'Reject',
  consentSettings: 'Preferences',
  consentSave: 'Save choice',
  consentFunctional: 'Necessary',
  consentStats: 'Statistics',
  consentMarketing: 'Marketing',
  consentFunctionalNote: 'Always on. Without these the site does not work.',

  // Shop surface. The demo catalogue is labelled in every market, because a
  // disclaimer that only exists in English is not a disclaimer for a reader in
  // Bucharest looking at a euro price.
  // Hub descriptions. These lived hard coded in generateMetadata, which meant
  // the German and Romanian hubs shipped an English description to six pages.
  // They belong in the string table with everything else that is written per
  // market.
  hubMeta: {
    esim: 'Mobile data for over 120 destinations, with the coverage notes and the limitations written down before you buy.',
    regions: 'Regional overviews for every part of the world Livdar covers.',
    guides: 'Travel connectivity guides: how an eSIM works, installing one, and when you do not need one at all.',
  },
  shop: {
    tab: 'Shop',
    searchPlaceholder: 'Search destination',
    allSuppliers: 'All',
    supplierLabel: 'Supplier',
    filters: {
      popular: 'Popular',
      under10: 'Under 10 EUR',
      tenGb: '10+ GB',
      thirtyDays: '30 days',
      unlimited: 'Unlimited',
      fiveG: '5G',
    },
    countShown: '{count} plans shown',
    viewAll: 'View all',
    showMore: 'Show more',
    sortBy: 'Sort by {value}',
    sort: { popular: 'Popular', priceLow: 'Lowest price', priceHigh: 'Highest price', dataHigh: 'Most data' },
    badges: {
      bestValue: 'Best value',
      popular: 'Popular',
      largeData: 'Large data',
      travellerPick: 'Traveller pick',
      premium: 'Premium',
      topPick: 'Top pick',
      unlimited: 'Unlimited',
    },
    demoBadge: 'Sample',
    demoNoticeTitle: 'Sample catalogue.',
    demoNoticeBody: 'Prices, data and validity below are examples used to test which destinations people need. They are not confirmed offers, and Livdar is not a partner of the suppliers named. Nothing here can be bought yet.',
    view: 'View',
    save: 'Save',
    noResults: 'No sample plan matches that filter',
    detailTitle: 'Sample plan',
    factData: 'Data',
    factValidity: 'Validity',
    factNetwork: 'Network',
    readAbout: 'Read about {name}',
  },
  buySteps: {
    title: 'Buy in three steps',
    sub: 'Get online abroad in minutes.',
    link: 'How it works',
    steps: [
      { title: 'Choose a destination', body: 'Find your country or region.' },
      { title: 'Compare plans', body: 'See data, duration and coverage notes.' },
      { title: 'Continue to checkout', body: 'Activation opens when a supplier is connected.' },
    ],
  },
  shopByDestination: { title: 'Shop by destination', sub: 'Quick visual entry points.' },
  regionalEsims: { title: 'Regional eSIMs', sub: 'For multi country trips.' },
  tools: {
    title: 'Travel tools',
    sub: 'Plan smarter. Travel further.',
    tabs: { cost: 'Travel cost', advisor: 'eSIM advisor', advice: 'Travel advice', card: 'Travel card' },
    cost: {
      title: 'Travel cost calculator',
      sub: 'Estimate your trip budget in seconds.',
      destination: 'Destination',
      days: 'Days',
      stay: 'Accommodation / day',
      food: 'Food / day',
      transport: 'Transport / day',
      esim: 'Connectivity',
      activities: 'Include activities',
      activitiesSub: 'Tours, attractions and entry fees.',
      cta: 'Calculate my travel budget',
      resultTitle: 'Estimated trip budget',
      perDay: 'Per day',
      total: 'Total for {days} days',
      note: 'An estimate from the numbers you entered. It is arithmetic, not a quote.',
    },
    advisor: {
      title: 'eSIM advisor',
      sub: 'Estimate how much data your trip may need.',
      days: 'Days',
      usage: 'Usage',
      usageOptions: { light: 'Light', medium: 'Medium', heavy: 'Heavy' },
      hotspot: 'I use hotspot',
      hotspotSub: 'Adds a buffer for laptops or shared connections.',
      cta: 'Recommend data',
      resultTitle: 'Suggested data allowance',
      unlimited: 'Unlimited',
      resultNote: 'Planning estimate only. Compare it with a confirmed supplier plan before buying.',
    },
    advice: {
      title: 'Travel advice',
      sub: 'Useful checks before you arrive.',
      destination: 'Destination',
      cta: 'Show advice',
      items: [
        { title: 'Internet', body: 'Check local 4G and 5G coverage in {destination}, then install and test your eSIM before departure.' },
        { title: 'Roaming', body: 'Check your home operator settings and turn off data roaming on the primary SIM if you do not need it.' },
        { title: 'Transport', body: 'Save offline maps for {destination} and check local public transport or ride apps before arrival.' },
        { title: 'Money', body: 'Keep a backup payment method and check whether small purchases in {destination} commonly need cash.' },
        { title: 'Power', body: 'Verify the plug type and voltage used in {destination} before packing an adapter.' },
      ],
    },
    card: {
      title: 'Travel card generator',
      sub: 'Create a social card for your trip.',
      destination: 'Destination',
      days: 'Days',
      budget: 'Budget in EUR',
      data: 'eSIM data',
      generate: 'Generate card',
      download: 'Download PNG',
      share: 'Share',
      shareTitle: 'My Livdar trip',
      dayLabel: 'days',
      budgetLabel: 'budget',
      dataLabel: 'eSIM',
    },
  },
};

const DE = {
  ...EN,
  selectPlan: 'Diesen Tarif wählen',
  continueToCheckout: 'Weiter zur Kasse',
  backToPlans: 'Zurück zu den Tarifen',
  planDetailTitle: 'Tarifdetails',
  planSlotTitle: 'Tarifplatz',
  planSlotAria: 'Tariffelder, Werte folgen sobald ein Anbieter angebunden ist',
  planSlotNote: 'Das sind die Felder, die jeder Tarif tragen wird. Wir lassen sie leer, statt sie mit Zahlen zu füllen, die wir noch nicht einhalten können.',
  valueNotSet: 'noch nicht gesetzt',
  planFields: { data: 'Datenvolumen', validity: 'Laufzeit', hotspot: 'Hotspot', network: 'Netze', price: 'Preis' },
  checkoutUnavailableTitle: 'Dieser Tarif ist noch nicht sofort aktivierbar',
  checkoutUnavailableBody: 'Es ist kein Anbieter angebunden, also gibt es nichts zu aktivieren und nichts zu berechnen. Sagen Sie uns, wohin Sie reisen, und Sie erfahren als Erste, wenn dieses Reiseziel verfügbar ist.',
  checkoutNoPaymentNote: 'Auf dieser Seite wird keine Zahlung entgegengenommen. Nichts, was Sie geklickt haben, hat Sie etwas gekostet.',
  filterAll: 'Alle Reiseziele',
  filterRegion: 'Nach Region filtern',
  emptyResults: 'Dazu passt noch nichts',
  regionDestinationsHeading: 'Alle {count} Reiseziele in {name}',
  nav: { esim: 'Reiseziele', regions: 'Regionen', guides: 'Ratgeber', compare: 'Vergleich', compatibility: 'Kompatibilität' },
  searchLabel: 'Wohin geht die Reise?',
  searchPlaceholder: 'Land oder Region suchen',
  searchHint: 'Reiseziel eintippen',
  searchEmpty: 'Dazu gibt es noch kein Reiseziel',
  searchOpen: 'Suche öffnen',
  viewPlans: 'Tarife ansehen',
  checkAvailability: 'Verfügbarkeit prüfen',
  notifyMe: 'Benachrichtigen, sobald Tarife live sind',
  compareOptions: 'Optionen vergleichen',
  seeConnectivity: 'Verbindungsoptionen ansehen',
  popularDestinations: 'Beliebte Reiseziele',
  allDestinations: 'Alle Reiseziele',
  regionalPlans: 'Regionale Tarife',
  howItWorks: 'So funktioniert es',
  faq: 'Häufige Fragen',
  relatedDestinations: 'Reiseziele in der Nähe',
  networksLabel: 'Netze im Land',
  callingCode: 'Vorwahl',
  regionLabel: 'Region',
  languageLabel: 'Sprache',
  languageSwitch: 'Sprache wechseln',
  backToHub: 'Alle eSIM Reiseziele',
  notConnectedTitle: 'Tarife sind noch nicht im Verkauf',
  notConnectedBody: 'Wir prüfen zuerst, welche Reiseziele wirklich gebraucht werden, bevor wir einen Anbieter anbinden. Sag uns, wohin du reist, und du erfährst als Erster, wenn es dafür Tarife gibt.',
  destinationsCount: 'Reiseziele',
  languagesCount: 'Sprachen',
  footerLegal: 'Rechtliches',
  footerProduct: 'Produkt',
  footerCompany: 'Unternehmen',
  privacy: 'Datenschutz',
  cookies: 'Cookies',
  terms: 'AGB',
  contact: 'Kontakt',
  about: 'Ueber Livdar',
  consentTitle: 'Deine Cookie Entscheidung',
  consentBody: 'Notwendige Cookies braucht die Seite zum Funktionieren. Statistik und Marketing laufen nur, wenn du zustimmst.',
  consentAccept: 'Alle akzeptieren',
  consentReject: 'Ablehnen',
  consentSettings: 'Einstellungen',
  consentSave: 'Auswahl speichern',
  consentFunctional: 'Notwendig',
  consentStats: 'Statistik',
  consentMarketing: 'Marketing',
  consentFunctionalNote: 'Immer aktiv. Ohne diese funktioniert die Seite nicht.',

  hubMeta: {
    esim: 'Mobile Daten für über 120 Reiseziele, mit den Hinweisen zur Abdeckung und den Einschränkungen, bevor du kaufst.',
    regions: 'Regionale Übersichten für jeden Teil der Welt, den Livdar abdeckt.',
    guides: 'Ratgeber zur Konnektivität auf Reisen: wie ein eSIM funktioniert, wie du es einrichtest, und wann du gar keins brauchst.',
  },
  shop: {
    tab: 'Shop',
    searchPlaceholder: 'Reiseziel suchen',
    allSuppliers: 'Alle',
    supplierLabel: 'Anbieter',
    filters: {
      popular: 'Beliebt',
      under10: 'Unter 10 EUR',
      tenGb: 'Ab 10 GB',
      thirtyDays: '30 Tage',
      unlimited: 'Unbegrenzt',
      fiveG: '5G',
    },
    countShown: '{count} Tarife angezeigt',
    viewAll: 'Alle ansehen',
    showMore: 'Mehr anzeigen',
    sortBy: 'Sortiert nach {value}',
    sort: { popular: 'Beliebtheit', priceLow: 'Niedrigster Preis', priceHigh: 'Höchster Preis', dataHigh: 'Meiste Daten' },
    badges: {
      bestValue: 'Bestes Angebot',
      popular: 'Beliebt',
      largeData: 'Viel Datenvolumen',
      travellerPick: 'Reise-Tipp',
      premium: 'Premium',
      topPick: 'Top-Tipp',
      unlimited: 'Unbegrenzt',
    },
    demoBadge: 'Beispiel',
    demoNoticeTitle: 'Beispielkatalog.',
    demoNoticeBody: 'Preise, Datenvolumen und Laufzeiten unten sind Beispiele, mit denen wir testen, welche Reiseziele wirklich gebraucht werden. Es sind keine bestätigten Angebote, und Livdar ist kein Partner der genannten Anbieter. Kaufen lässt sich hier noch nichts.',
    view: 'Ansehen',
    save: 'Merken',
    noResults: 'Kein Beispieltarif passt zu diesem Filter',
    detailTitle: 'Beispieltarif',
    factData: 'Daten',
    factValidity: 'Laufzeit',
    factNetwork: 'Netz',
    readAbout: 'Mehr zu {name}',
  },
  buySteps: {
    title: 'In drei Schritten zum eSIM',
    sub: 'Im Ausland in Minuten online.',
    link: 'So funktioniert es',
    steps: [
      { title: 'Reiseziel wählen', body: 'Finde dein Land oder deine Region.' },
      { title: 'Tarife vergleichen', body: 'Datenvolumen, Laufzeit und Hinweise zur Abdeckung.' },
      { title: 'Weiter zur Kasse', body: 'Die Aktivierung öffnet, sobald ein Anbieter angebunden ist.' },
    ],
  },
  shopByDestination: { title: 'Nach Reiseziel', sub: 'Der schnelle Einstieg.' },
  regionalEsims: { title: 'Regionale eSIMs', sub: 'Für Reisen durch mehrere Länder.' },
  tools: {
    title: 'Reise-Tools',
    sub: 'Besser planen. Weiter reisen.',
    tabs: { cost: 'Reisekosten', advisor: 'eSIM-Berater', advice: 'Reisetipps', card: 'Reisekarte' },
    cost: {
      title: 'Reisekosten-Rechner',
      sub: 'Schätze dein Reisebudget in Sekunden.',
      destination: 'Reiseziel',
      days: 'Tage',
      stay: 'Unterkunft / Tag',
      food: 'Essen / Tag',
      transport: 'Transport / Tag',
      esim: 'Konnektivität',
      activities: 'Aktivitäten einrechnen',
      activitiesSub: 'Touren, Sehenswürdigkeiten und Eintritte.',
      cta: 'Mein Reisebudget berechnen',
      resultTitle: 'Geschätztes Reisebudget',
      perDay: 'Pro Tag',
      total: 'Gesamt für {days} Tage',
      note: 'Eine Schätzung aus deinen eigenen Zahlen. Rechnung, kein Angebot.',
    },
    advisor: {
      title: 'eSIM-Berater',
      sub: 'Schätze, wie viele Daten deine Reise brauchen könnte.',
      days: 'Tage',
      usage: 'Nutzung',
      usageOptions: { light: 'Leicht', medium: 'Mittel', heavy: 'Stark' },
      hotspot: 'Ich nutze Hotspot',
      hotspotSub: 'Fügt einen Puffer für Laptops oder geteilte Verbindungen hinzu.',
      cta: 'Daten empfehlen',
      resultTitle: 'Empfohlenes Datenvolumen',
      unlimited: 'Unbegrenzt',
      resultNote: 'Nur eine Planungsschätzung. Vor dem Kauf mit einem bestätigten Anbietertarif vergleichen.',
    },
    advice: {
      title: 'Reisetipps',
      sub: 'Nützliche Checks vor der Ankunft.',
      destination: 'Reiseziel',
      cta: 'Tipps anzeigen',
      items: [
        { title: 'Internet', body: 'Prüfe die lokale 4G und 5G Abdeckung in {destination} und teste die eSIM vor der Abreise.' },
        { title: 'Roaming', body: 'Prüfe die Einstellungen deines Heimanbieters und schalte Datenroaming auf der Haupt-SIM aus, wenn du es nicht brauchst.' },
        { title: 'Transport', body: 'Speichere Offline-Karten für {destination} und prüfe lokale Verkehrs- oder Fahrdienst-Apps vor der Ankunft.' },
        { title: 'Geld', body: 'Halte eine zweite Zahlungsmethode bereit und prüfe, ob kleine Einkäufe in {destination} oft Bargeld brauchen.' },
        { title: 'Strom', body: 'Prüfe Steckertyp und Spannung in {destination}, bevor du einen Adapter einpackst.' },
      ],
    },
    card: {
      title: 'Reisekarten-Generator',
      sub: 'Erstelle eine Social Card für deine Reise.',
      destination: 'Reiseziel',
      days: 'Tage',
      budget: 'Budget in EUR',
      data: 'eSIM-Daten',
      generate: 'Karte erstellen',
      download: 'PNG laden',
      share: 'Teilen',
      shareTitle: 'Meine Livdar Reise',
      dayLabel: 'Tage',
      budgetLabel: 'Budget',
      dataLabel: 'eSIM',
    },
  },
};

const RO = {
  ...EN,
  selectPlan: 'Alege planul',
  continueToCheckout: 'Continuă spre finalizare',
  backToPlans: 'Înapoi la planuri',
  planDetailTitle: 'Detalii plan',
  planSlotTitle: 'Loc de plan',
  planSlotAria: 'Câmpurile planului, valorile apar când se conectează un furnizor',
  planSlotNote: 'Acestea sunt câmpurile pe care le va avea fiecare plan. Le lăsăm goale în loc să le umplem cu cifre pe care încă nu le putem respecta.',
  valueNotSet: 'încă nestabilit',
  planFields: { data: 'Date', validity: 'Valabilitate', hotspot: 'Hotspot', network: 'Rețele', price: 'Preț' },
  checkoutUnavailableTitle: 'Planul acesta nu se poate activa încă pe loc',
  checkoutUnavailableBody: 'Nu este conectat niciun furnizor, deci nu există ce să se activeze și nu există ce să îți fie taxat. Spune-ne unde pleci și afli primul când destinația devine disponibilă.',
  checkoutNoPaymentNote: 'Pe site-ul acesta nu se încasează nicio plata. Nimic din ce ai apăsat nu te-a costat nimic.',
  filterAll: 'Toate destinațiile',
  filterRegion: 'Filtrează după regiune',
  emptyResults: 'Nu se potrivește nimic încă',
  regionDestinationsHeading: 'Toate cele {count} destinații din {name}',
  nav: { esim: 'Destinații', regions: 'Regiuni', guides: 'Ghiduri', compare: 'Comparații', compatibility: 'Compatibilitate' },
  searchLabel: 'Unde pleci?',
  searchPlaceholder: 'Caută o țară sau o regiune',
  searchHint: 'Scrie destinația',
  searchEmpty: 'Nicio destinație nu se potrivește încă',
  searchOpen: 'Deschide căutarea',
  viewPlans: 'Vezi planurile',
  checkAvailability: 'Verifică disponibilitatea',
  notifyMe: 'Anunță-mă când apar planuri',
  compareOptions: 'Compară opțiunile',
  seeConnectivity: 'Vezi opțiunile de conectare',
  popularDestinations: 'Destinații căutate',
  allDestinations: 'Toate destinațiile',
  regionalPlans: 'Planuri regionale',
  howItWorks: 'Cum funcționează',
  faq: 'Întrebări frecvente',
  relatedDestinations: 'Destinații apropiate',
  networksLabel: 'Rețelele din țară',
  callingCode: 'Prefix telefonic',
  regionLabel: 'Regiune',
  languageLabel: 'Limba',
  languageSwitch: 'Schimbă limba',
  backToHub: 'Toate destinațiile eSIM',
  notConnectedTitle: 'Planurile nu sunt încă la vânzare',
  notConnectedBody: 'Testăm întâi pentru ce destinații există cerere reală, înainte să conectăm un furnizor. Spune-ne unde pleci și afli primul când apar planuri pentru destinația ta.',
  destinationsCount: 'destinatii',
  languagesCount: 'limbi',
  footerLegal: 'Legal',
  footerProduct: 'Produs',
  footerCompany: 'Companie',
  privacy: 'Confidențialitate',
  cookies: 'Cookie-uri',
  terms: 'Termeni',
  contact: 'Contact',
  about: 'Despre Livdar',
  consentTitle: 'Alegerea ta despre cookie-uri',
  consentBody: 'Folosim cookie-uri necesare ca site-ul să funcționeze. Cele de statistica și marketing rulează doar dacă le accepți.',
  consentAccept: 'Acceptă tot',
  consentReject: 'Refuză',
  consentSettings: 'Preferințe',
  consentSave: 'Salvează alegerea',
  consentFunctional: 'Necesare',
  consentStats: 'Statistica',
  consentMarketing: 'Marketing',
  consentFunctionalNote: 'Mereu active. Fără ele site-ul nu funcționează.',

  hubMeta: {
    esim: 'Date mobile pentru peste 120 de destinații, cu notele de acoperire și limitările scrise înainte să cumperi.',
    regions: 'Prezentări regionale pentru fiecare parte a lumii pe care o acoperă Livdar.',
    guides: 'Ghiduri de conectivitate în călătorie: cum funcționează un eSIM, cum îl instalezi și când nu ai nevoie de unul.',
  },
  shop: {
    tab: 'Magazin',
    searchPlaceholder: 'Caută o destinație',
    allSuppliers: 'Toți',
    supplierLabel: 'Furnizor',
    filters: {
      popular: 'Populare',
      under10: 'Sub 10 EUR',
      tenGb: 'Peste 10 GB',
      thirtyDays: '30 de zile',
      unlimited: 'Nelimitat',
      fiveG: '5G',
    },
    countShown: '{count} planuri afișate',
    viewAll: 'Vezi tot',
    showMore: 'Arată mai multe',
    sortBy: 'Ordonat după {value}',
    sort: { popular: 'Popularitate', priceLow: 'Cel mai mic preț', priceHigh: 'Cel mai mare preț', dataHigh: 'Cei mai mulți GB' },
    badges: {
      bestValue: 'Cel mai bun raport',
      popular: 'Popular',
      largeData: 'Mulți GB',
      travellerPick: 'Alegerea călătorilor',
      premium: 'Premium',
      topPick: 'Recomandat',
      unlimited: 'Nelimitat',
    },
    demoBadge: 'Exemplu',
    demoNoticeTitle: 'Catalog demonstrativ.',
    demoNoticeBody: 'Prețurile, volumele de date și valabilitatea de mai jos sunt exemple cu care testăm ce destinații sunt cerute cu adevărat. Nu sunt oferte confirmate, iar Livdar nu este partener al furnizorilor menționați. Nimic de aici nu se poate cumpăra încă.',
    view: 'Vezi',
    save: 'Salvează',
    noResults: 'Niciun plan demonstrativ nu se potrivește cu filtrul',
    detailTitle: 'Plan demonstrativ',
    factData: 'Date',
    factValidity: 'Valabilitate',
    factNetwork: 'Rețea',
    readAbout: 'Citește despre {name}',
  },
  buySteps: {
    title: 'Cumperi în trei pași',
    sub: 'Ești online în străinătate în câteva minute.',
    link: 'Cum funcționează',
    steps: [
      { title: 'Alege destinația', body: 'Găsește-ți țara sau regiunea.' },
      { title: 'Compară planurile', body: 'Vezi datele, durata și notele de acoperire.' },
      { title: 'Continuă spre finalizare', body: 'Activarea se deschide când conectăm un furnizor.' },
    ],
  },
  shopByDestination: { title: 'Cumpără după destinație', sub: 'Puncte rapide de intrare.' },
  regionalEsims: { title: 'eSIM-uri regionale', sub: 'Pentru călătorii prin mai multe țări.' },
  tools: {
    title: 'Unelte de călătorie',
    sub: 'Planifici mai bine. Ajungi mai departe.',
    tabs: { cost: 'Costul călătoriei', advisor: 'Consilier eSIM', advice: 'Sfaturi de călătorie', card: 'Card de călătorie' },
    cost: {
      title: 'Calculator pentru costul călătoriei',
      sub: 'Estimează bugetul călătoriei în câteva secunde.',
      destination: 'Destinație',
      days: 'Zile',
      stay: 'Cazare / zi',
      food: 'Mâncare / zi',
      transport: 'Transport / zi',
      esim: 'Conectivitate',
      activities: 'Include activitățile',
      activitiesSub: 'Tururi, obiective și bilete de intrare.',
      cta: 'Calculează-mi bugetul',
      resultTitle: 'Buget estimat pentru călătorie',
      perDay: 'Pe zi',
      total: 'Total pentru {days} zile',
      note: 'O estimare din cifrele introduse de tine. Este aritmetică, nu o ofertă.',
    },
    advisor: {
      title: 'Consilier eSIM',
      sub: 'Estimează de câte date ai putea avea nevoie în călătorie.',
      days: 'Zile',
      usage: 'Consum',
      usageOptions: { light: 'Redus', medium: 'Mediu', heavy: 'Intens' },
      hotspot: 'Folosesc hotspot',
      hotspotSub: 'Adaugă o rezervă pentru laptop sau conexiuni partajate.',
      cta: 'Recomandă date',
      resultTitle: 'Volum de date sugerat',
      unlimited: 'Nelimitat',
      resultNote: 'Este doar o estimare de planificare. Compar-o cu un plan confirmat de furnizor înainte de cumpărare.',
    },
    advice: {
      title: 'Sfaturi de călătorie',
      sub: 'Verificări utile înainte să ajungi.',
      destination: 'Destinație',
      cta: 'Arată sfaturile',
      items: [
        { title: 'Internet', body: 'Verifică acoperirea locală 4G și 5G în {destination}, apoi instalează și testează eSIM-ul înainte de plecare.' },
        { title: 'Roaming', body: 'Verifică setările operatorului de acasă și oprește roamingul de date pe SIM-ul principal dacă nu ai nevoie de el.' },
        { title: 'Transport', body: 'Salvează hărți offline pentru {destination} și verifică aplicațiile locale de transport înainte să ajungi.' },
        { title: 'Bani', body: 'Păstrează o metodă de plată de rezervă și verifică dacă plățile mici în {destination} necesită numerar.' },
        { title: 'Prize', body: 'Verifică tipul prizei și tensiunea folosite în {destination} înainte să iei un adaptor.' },
      ],
    },
    card: {
      title: 'Generator card de călătorie',
      sub: 'Creează un card social pentru călătoria ta.',
      destination: 'Destinație',
      days: 'Zile',
      budget: 'Buget în EUR',
      data: 'Date eSIM',
      generate: 'Generează cardul',
      download: 'Descarcă PNG',
      share: 'Distribuie',
      shareTitle: 'Călătoria mea Livdar',
      dayLabel: 'zile',
      budgetLabel: 'buget',
      dataLabel: 'eSIM',
    },
  },
};

const TABLE = { en: EN, de: DE, ro: RO };

export function ui(locale) {
  return TABLE[locale] || EN;
}

// The exact strings the shop island needs, and nothing else.
//
// Handing a client component the whole interface table is easy and expensive:
// the table is serialised into the payload of every page that renders the
// island, and most of it is for pages the island knows nothing about. This is
// the contract instead, so what crosses the boundary is visible in one place
// and grows only when somebody means it to.
export function shopStrings(locale) {
  const t = ui(locale);
  return {
    shop: t.shop,
    searchLabel: t.searchLabel,
    filterRegion: t.filterRegion,
    selectPlan: t.selectPlan,
    continueToCheckout: t.continueToCheckout,
    backToPlans: t.backToPlans,
    notifyMe: t.notifyMe,
    checkoutUnavailableTitle: t.checkoutUnavailableTitle,
    checkoutUnavailableBody: t.checkoutUnavailableBody,
    checkoutNoPaymentNote: t.checkoutNoPaymentNote,
    notConnectedBody: t.notConnectedBody,
  };
}

export function toolStrings(locale) {
  return { tools: ui(locale).tools };
}
