// Interface strings only. These are chrome: navigation, buttons, labels.
// Editorial copy never lives here, because editorial copy is written per market
// and not translated.

const EN = {
  regionDestinationsHeading: (name, count) => 'All ' + count + ' destinations in ' + name,
  regionTitle: (name, count) => name + ' eSIM: ' + count + ' destinations covered | Livdar',
  regionDescription: (name) => 'Every destination Livdar covers in ' + name + ', with the networks that run each country and the coverage notes that matter.',
  compatibilityTitle: 'eSIM compatibility: does your phone support it | Livdar',
  compatibilityDescription: 'Which phones support eSIM, how to check your own device in ten seconds, and what dual SIM actually changes.',
  brand: 'Livdar',
  product: 'eSIM',
  skipToContent: 'Skip to content',
  nav: { esim: 'Destinations', regions: 'Regions', guides: 'Guides', compare: 'Compare', compatibility: 'Compatibility' },
  searchLabel: 'Where are you going?',
  searchPlaceholder: 'Search a country or region',
  searchHint: 'Start typing a destination',
  searchEmpty: 'No destination matches that yet',
  searchOpen: 'Open search',
  viewPlans: 'View plans',
  checkAvailability: 'Check availability',
  notifyMe: 'Notify me when plans go live',
  compareOptions: 'Compare options',
  seeConnectivity: 'See connectivity options',
  popularDestinations: 'Popular destinations',
  allDestinations: 'All destinations',
  regionalPlans: 'Regional plans',
  howItWorks: 'How it works',
  faq: 'Common questions',
  relatedDestinations: 'Nearby destinations',
  networksLabel: 'Networks in the country',
  callingCode: 'Dialling code',
  regionLabel: 'Region',
  languageLabel: 'Language',
  languageSwitch: 'Change language',
  backToHub: 'All eSIM destinations',
  notConnectedTitle: 'Plans are not on sale yet',
  notConnectedBody: 'We are testing which destinations people actually need before we connect a supplier. Tell us where you are going and you will be first to know when plans for that destination go live.',
  destinationsCount: 'destinations',
  languagesCount: 'languages',
  footerLegal: 'Legal',
  footerProduct: 'Product',
  footerCompany: 'Company',
  privacy: 'Privacy',
  cookies: 'Cookies',
  terms: 'Terms',
  contact: 'Contact',
  about: 'About Livdar',
  consentTitle: 'Your choice on cookies',
  consentBody: 'We use cookies that are needed for the site to work. Statistics and marketing cookies only run if you allow them.',
  consentAccept: 'Accept all',
  consentReject: 'Reject',
  consentSettings: 'Preferences',
  consentSave: 'Save choice',
  consentFunctional: 'Necessary',
  consentStats: 'Statistics',
  consentMarketing: 'Marketing',
  consentFunctionalNote: 'Always on. Without these the site does not work.',
};

const DE = {
  ...EN,
  regionDestinationsHeading: (name, count) => 'Alle ' + count + ' Reiseziele in ' + name,
  regionTitle: (name, count) => name + ' eSIM: ' + count + ' Reiseziele abgedeckt | Livdar',
  regionDescription: (name) => 'Alle Reiseziele, die Livdar in ' + name + ' abdeckt, mit den Netzen jedes Landes und den Hinweisen, die wirklich zaehlen.',
  compatibilityTitle: 'eSIM Kompatibilitaet: unterstuetzt dein Handy das | Livdar',
  compatibilityDescription: 'Welche Handys eSIM unterstuetzen, wie du dein eigenes Geraet in zehn Sekunden pruefst und was Dual SIM tatsaechlich aendert.',
  nav: { esim: 'Reiseziele', regions: 'Regionen', guides: 'Ratgeber', compare: 'Vergleich', compatibility: 'Kompatibilitaet' },
  searchLabel: 'Wohin geht die Reise?',
  searchPlaceholder: 'Land oder Region suchen',
  searchHint: 'Reiseziel eintippen',
  searchEmpty: 'Dazu gibt es noch kein Reiseziel',
  searchOpen: 'Suche oeffnen',
  viewPlans: 'Tarife ansehen',
  checkAvailability: 'Verfuegbarkeit pruefen',
  notifyMe: 'Benachrichtigen, sobald Tarife live sind',
  compareOptions: 'Optionen vergleichen',
  seeConnectivity: 'Verbindungsoptionen ansehen',
  popularDestinations: 'Beliebte Reiseziele',
  allDestinations: 'Alle Reiseziele',
  regionalPlans: 'Regionale Tarife',
  howItWorks: 'So funktioniert es',
  faq: 'Haeufige Fragen',
  relatedDestinations: 'Reiseziele in der Naehe',
  networksLabel: 'Netze im Land',
  callingCode: 'Vorwahl',
  regionLabel: 'Region',
  languageLabel: 'Sprache',
  languageSwitch: 'Sprache wechseln',
  backToHub: 'Alle eSIM Reiseziele',
  notConnectedTitle: 'Tarife sind noch nicht im Verkauf',
  notConnectedBody: 'Wir pruefen zuerst, welche Reiseziele wirklich gebraucht werden, bevor wir einen Anbieter anbinden. Sag uns, wohin du reist, und du erfaehrst als Erster, wenn es dafuer Tarife gibt.',
  destinationsCount: 'Reiseziele',
  languagesCount: 'Sprachen',
  footerLegal: 'Rechtliches',
  footerProduct: 'Produkt',
  footerCompany: 'Unternehmen',
  privacy: 'Datenschutz',
  cookies: 'Cookies',
  terms: 'AGB',
  contact: 'Kontakt',
  about: 'Ueber Livdar',
  consentTitle: 'Deine Cookie Entscheidung',
  consentBody: 'Notwendige Cookies braucht die Seite zum Funktionieren. Statistik und Marketing laufen nur, wenn du zustimmst.',
  consentAccept: 'Alle akzeptieren',
  consentReject: 'Ablehnen',
  consentSettings: 'Einstellungen',
  consentSave: 'Auswahl speichern',
  consentFunctional: 'Notwendig',
  consentStats: 'Statistik',
  consentMarketing: 'Marketing',
  consentFunctionalNote: 'Immer aktiv. Ohne diese funktioniert die Seite nicht.',
};

const RO = {
  ...EN,
  regionDestinationsHeading: (name, count) => 'Toate cele ' + count + ' destinatii din ' + name,
  regionTitle: (name, count) => name + ' eSIM: ' + count + ' destinatii acoperite | Livdar',
  regionDescription: (name) => 'Toate destinatiile pe care Livdar le acopera in ' + name + ', cu retelele din fiecare tara si notele de acoperire care conteaza.',
  compatibilityTitle: 'Compatibilitate eSIM: telefonul tau suporta | Livdar',
  compatibilityDescription: 'Ce telefoane suporta eSIM, cum verifici propriul aparat in zece secunde si ce schimba de fapt dual SIM.',
  nav: { esim: 'Destinatii', regions: 'Regiuni', guides: 'Ghiduri', compare: 'Comparatii', compatibility: 'Compatibilitate' },
  searchLabel: 'Unde pleci?',
  searchPlaceholder: 'Cauta o tara sau o regiune',
  searchHint: 'Scrie destinatia',
  searchEmpty: 'Nicio destinatie nu se potriveste inca',
  searchOpen: 'Deschide cautarea',
  viewPlans: 'Vezi planurile',
  checkAvailability: 'Verifica disponibilitatea',
  notifyMe: 'Anunta-ma cand apar planuri',
  compareOptions: 'Compara optiunile',
  seeConnectivity: 'Vezi optiunile de conectare',
  popularDestinations: 'Destinatii cautate',
  allDestinations: 'Toate destinatiile',
  regionalPlans: 'Planuri regionale',
  howItWorks: 'Cum functioneaza',
  faq: 'Intrebari frecvente',
  relatedDestinations: 'Destinatii apropiate',
  networksLabel: 'Retelele din tara',
  callingCode: 'Prefix telefonic',
  regionLabel: 'Regiune',
  languageLabel: 'Limba',
  languageSwitch: 'Schimba limba',
  backToHub: 'Toate destinatiile eSIM',
  notConnectedTitle: 'Planurile nu sunt inca la vanzare',
  notConnectedBody: 'Testam intai pentru ce destinatii exista cerere reala, inainte sa conectam un furnizor. Spune-ne unde pleci si afli primul cand apar planuri pentru destinatia ta.',
  destinationsCount: 'destinatii',
  languagesCount: 'limbi',
  footerLegal: 'Legal',
  footerProduct: 'Produs',
  footerCompany: 'Companie',
  privacy: 'Confidentialitate',
  cookies: 'Cookie-uri',
  terms: 'Termeni',
  contact: 'Contact',
  about: 'Despre Livdar',
  consentTitle: 'Alegerea ta despre cookie-uri',
  consentBody: 'Folosim cookie-uri necesare ca site-ul sa functioneze. Cele de statistica si marketing ruleaza doar daca le accepti.',
  consentAccept: 'Accepta tot',
  consentReject: 'Refuza',
  consentSettings: 'Preferinte',
  consentSave: 'Salveaza alegerea',
  consentFunctional: 'Necesare',
  consentStats: 'Statistica',
  consentMarketing: 'Marketing',
  consentFunctionalNote: 'Mereu active. Fara ele site-ul nu functioneaza.',
};

const TABLE = { en: EN, de: DE, ro: RO };

export function ui(locale) {
  return TABLE[locale] || EN;
}
