// Interface strings only. These are chrome: navigation, buttons, labels.
//
// Every value in this table must be JSON serialisable. The whole object is
// handed to client components such as the consent banner and the plan panel,
// and React refuses to send a function across that boundary. A function here
// fails the build at prerender time, which is exactly what happened once.
// Use {placeholder} tokens and interpolate at the call site instead.
// Editorial copy never lives here, because editorial copy is written per market
// and not translated.

const EN = {
  selectPlan: 'Select this plan',
  continueToCheckout: 'Continue to checkout',
  backToPlans: 'Back to plans',
  planDetailTitle: 'Plan details',
  planSlotTitle: 'Plan slot',
  planSlotAria: 'Plan fields, values arrive when a supplier is connected',
  planSlotNote: 'These are the fields every plan will carry. We leave them empty rather than fill them with numbers we cannot honour yet.',
  valueNotSet: 'not set yet',
  planFields: { data: 'Data', validity: 'Validity', hotspot: 'Hotspot', network: 'Networks', price: 'Price' },
  checkoutUnavailableTitle: 'This plan is not available for instant activation yet',
  checkoutUnavailableBody: 'No supplier is connected, so there is nothing to activate and nothing to charge you for. Tell us where you are going and you will be first to know when this destination goes live.',
  checkoutNoPaymentNote: 'No payment is taken on this site. Nothing you clicked has cost you anything.',
  filterAll: 'All destinations',
  filterRegion: 'Filter by region',
  emptyResults: 'Nothing matches that filter yet',
  regionDestinationsHeading: 'All {count} destinations in {name}',
  brand: 'Livdar',
  product: 'eSIM',
  skipToContent: 'Skip to content',
  nav: { esim: 'Destinations', regions: 'Regions', guides: 'Guides', compare: 'Compare', compatibility: 'Compatibility' },
  searchLabel: 'Where are you going?',
  searchPlaceholder: 'Search a country or region',
  searchHint: 'Start typing a destination',
  searchEmpty: 'No destination matches that yet',
  searchOpen: 'Open search',
  viewPlans: 'View plans',
  checkAvailability: 'Check availability',
  notifyMe: 'Notify me when plans go live',
  compareOptions: 'Compare options',
  seeConnectivity: 'See connectivity options',
  popularDestinations: 'Popular destinations',
  allDestinations: 'All destinations',
  regionalPlans: 'Regional plans',
  howItWorks: 'How it works',
  faq: 'Common questions',
  relatedDestinations: 'Nearby destinations',
  networksLabel: 'Networks in the country',
  callingCode: 'Dialling code',
  regionLabel: 'Region',
  languageLabel: 'Language',
  languageSwitch: 'Change language',
  backToHub: 'All eSIM destinations',
  notConnectedTitle: 'Plans are not on sale yet',
  notConnectedBody: 'We are testing which destinations people actually need before we connect a supplier. Tell us where you are going and you will be first to know when plans for that destination go live.',
  destinationsCount: 'destinations',
  languagesCount: 'languages',
  footerLegal: 'Legal',
  footerProduct: 'Product',
  footerCompany: 'Company',
  privacy: 'Privacy',
  cookies: 'Cookies',
  terms: 'Terms',
  contact: 'Contact',
  about: 'About Livdar',
  consentTitle: 'Your choice on cookies',
  consentBody: 'We use cookies that are needed for the site to work. Statistics and marketing cookies only run if you allow them.',
  consentAccept: 'Accept all',
  consentReject: 'Reject',
  consentSettings: 'Preferences',
  consentSave: 'Save choice',
  consentFunctional: 'Necessary',
  consentStats: 'Statistics',
  consentMarketing: 'Marketing',
  consentFunctionalNote: 'Always on. Without these the site does not work.',
};

const DE = {
  ...EN,
  selectPlan: 'Diesen Tarif wählen',
  continueToCheckout: 'Weiter zur Kasse',
  backToPlans: 'Zurück zu den Tarifen',
  planDetailTitle: 'Tarifdetails',
  planSlotTitle: 'Tarifplatz',
  planSlotAria: 'Tariffelder, Werte folgen sobald ein Anbieter angebunden ist',
  planSlotNote: 'Das sind die Felder, die jeder Tarif tragen wird. Wir lassen sie leer, statt sie mit Zahlen zu füllen, die wir noch nicht einhalten können.',
  valueNotSet: 'noch nicht gesetzt',
  planFields: { data: 'Datenvolumen', validity: 'Laufzeit', hotspot: 'Hotspot', network: 'Netze', price: 'Preis' },
  checkoutUnavailableTitle: 'Dieser Tarif ist noch nicht sofort aktivierbar',
  checkoutUnavailableBody: 'Es ist kein Anbieter angebunden, also gibt es nichts zu aktivieren und nichts zu berechnen. Sagen Sie uns, wohin Sie reisen, und Sie erfahren als Erste, wenn dieses Reiseziel verfügbar ist.',
  checkoutNoPaymentNote: 'Auf dieser Seite wird keine Zahlung entgegengenommen. Nichts, was Sie geklickt haben, hat Sie etwas gekostet.',
  filterAll: 'Alle Reiseziele',
  filterRegion: 'Nach Region filtern',
  emptyResults: 'Dazu passt noch nichts',
  regionDestinationsHeading: 'Alle {count} Reiseziele in {name}',
  nav: { esim: 'Reiseziele', regions: 'Regionen', guides: 'Ratgeber', compare: 'Vergleich', compatibility: 'Kompatibilität' },
  searchLabel: 'Wohin geht die Reise?',
  searchPlaceholder: 'Land oder Region suchen',
  searchHint: 'Reiseziel eintippen',
  searchEmpty: 'Dazu gibt es noch kein Reiseziel',
  searchOpen: 'Suche öffnen',
  viewPlans: 'Tarife ansehen',
  checkAvailability: 'Verfügbarkeit prüfen',
  notifyMe: 'Benachrichtigen, sobald Tarife live sind',
  compareOptions: 'Optionen vergleichen',
  seeConnectivity: 'Verbindungsoptionen ansehen',
  popularDestinations: 'Beliebte Reiseziele',
  allDestinations: 'Alle Reiseziele',
  regionalPlans: 'Regionale Tarife',
  howItWorks: 'So funktioniert es',
  faq: 'Häufige Fragen',
  relatedDestinations: 'Reiseziele in der Nähe',
  networksLabel: 'Netze im Land',
  callingCode: 'Vorwahl',
  regionLabel: 'Region',
  languageLabel: 'Sprache',
  languageSwitch: 'Sprache wechseln',
  backToHub: 'Alle eSIM Reiseziele',
  notConnectedTitle: 'Tarife sind noch nicht im Verkauf',
  notConnectedBody: 'Wir prüfen zuerst, welche Reiseziele wirklich gebraucht werden, bevor wir einen Anbieter anbinden. Sag uns, wohin du reist, und du erfährst als Erster, wenn es dafür Tarife gibt.',
  destinationsCount: 'Reiseziele',
  languagesCount: 'Sprachen',
  footerLegal: 'Rechtliches',
  footerProduct: 'Produkt',
  footerCompany: 'Unternehmen',
  privacy: 'Datenschutz',
  cookies: 'Cookies',
  terms: 'AGB',
  contact: 'Kontakt',
  about: 'Ueber Livdar',
  consentTitle: 'Deine Cookie Entscheidung',
  consentBody: 'Notwendige Cookies braucht die Seite zum Funktionieren. Statistik und Marketing laufen nur, wenn du zustimmst.',
  consentAccept: 'Alle akzeptieren',
  consentReject: 'Ablehnen',
  consentSettings: 'Einstellungen',
  consentSave: 'Auswahl speichern',
  consentFunctional: 'Notwendig',
  consentStats: 'Statistik',
  consentMarketing: 'Marketing',
  consentFunctionalNote: 'Immer aktiv. Ohne diese funktioniert die Seite nicht.',
};

const RO = {
  ...EN,
  selectPlan: 'Alege planul',
  continueToCheckout: 'Continuă spre finalizare',
  backToPlans: 'Înapoi la planuri',
  planDetailTitle: 'Detalii plan',
  planSlotTitle: 'Loc de plan',
  planSlotAria: 'Câmpurile planului, valorile apar când se conectează un furnizor',
  planSlotNote: 'Acestea sunt câmpurile pe care le va avea fiecare plan. Le lăsăm goale în loc să le umplem cu cifre pe care încă nu le putem respectă.',
  valueNotSet: 'încă nestabilit',
  planFields: { data: 'Date', validity: 'Valabilitate', hotspot: 'Hotspot', network: 'Rețele', price: 'Preț' },
  checkoutUnavailableTitle: 'Planul acesta nu se poate activa încă pe loc',
  checkoutUnavailableBody: 'Nu este conectat niciun furnizor, deci nu există ce să se activeze și nu există ce să îți fie taxat. Spune-ne unde pleci și afli primul când destinația devine disponibilă.',
  checkoutNoPaymentNote: 'Pe site-ul acesta nu se încasează nicio plata. Nimic din ce ai apăsat nu te-a costat nimic.',
  filterAll: 'Toate destinațiile',
  filterRegion: 'Filtrează după regiune',
  emptyResults: 'Nu se potrivește nimic încă',
  regionDestinationsHeading: 'Toate cele {count} destinații din {name}',
  nav: { esim: 'Destinații', regions: 'Regiuni', guides: 'Ghiduri', compare: 'Comparații', compatibility: 'Compatibilitate' },
  searchLabel: 'Unde pleci?',
  searchPlaceholder: 'Caută o țară sau o regiune',
  searchHint: 'Scrie destinația',
  searchEmpty: 'Nicio destinație nu se potrivește încă',
  searchOpen: 'Deschide căutarea',
  viewPlans: 'Vezi planurile',
  checkAvailability: 'Verifică disponibilitatea',
  notifyMe: 'Anunță-mă când apar planuri',
  compareOptions: 'Compară opțiunile',
  seeConnectivity: 'Vezi opțiunile de conectare',
  popularDestinations: 'Destinații căutate',
  allDestinations: 'Toate destinațiile',
  regionalPlans: 'Planuri regionale',
  howItWorks: 'Cum funcționează',
  faq: 'Întrebări frecvente',
  relatedDestinations: 'Destinații apropiate',
  networksLabel: 'Rețelele din țară',
  callingCode: 'Prefix telefonic',
  regionLabel: 'Regiune',
  languageLabel: 'Limba',
  languageSwitch: 'Schimbă limba',
  backToHub: 'Toate destinațiile eSIM',
  notConnectedTitle: 'Planurile nu sunt încă la vânzare',
  notConnectedBody: 'Testăm întâi pentru ce destinații există cerere reală, înainte să conectăm un furnizor. Spune-ne unde pleci și afli primul când apar planuri pentru destinația ta.',
  destinationsCount: 'destinatii',
  languagesCount: 'limbi',
  footerLegal: 'Legal',
  footerProduct: 'Produs',
  footerCompany: 'Companie',
  privacy: 'Confidențialitate',
  cookies: 'Cookie-uri',
  terms: 'Termeni',
  contact: 'Contact',
  about: 'Despre Livdar',
  consentTitle: 'Alegerea ta despre cookie-uri',
  consentBody: 'Folosim cookie-uri necesare ca site-ul să funcționeze. Cele de statistica și marketing rulează doar dacă le accepți.',
  consentAccept: 'Acceptă tot',
  consentReject: 'Refuză',
  consentSettings: 'Preferințe',
  consentSave: 'Salvează alegerea',
  consentFunctional: 'Necesare',
  consentStats: 'Statistica',
  consentMarketing: 'Marketing',
  consentFunctionalNote: 'Mereu active. Fără ele site-ul nu funcționează.',
};

const TABLE = { en: EN, de: DE, ro: RO };

export function ui(locale) {
  return TABLE[locale] || EN;
}
