#!/usr/bin/env python3
"""
The final report in the shape the brief asks for, assembled from the artifacts rather than retyped.

Every number here is read from a file another script wrote and verified: the manifest, the summary,
the QA report, the acceptance test, the rejected set, the parent assignment and the measurement
files in data/atlas/measurements. Nothing is entered by hand, so the report cannot drift from the
inventory the way a report typed from memory does.

Usage: final-brief-report.py
Writes reports/livdar-expiry-freeze-2026-09-30/1M-BRIEF-FINAL-REPORT.md
"""
import collections, csv, glob, gzip, json, os, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import entity_identity

ROOT = '/home/user/Livdar-eSim/'
OUT = ROOT + 'reports/livdar-expiry-freeze-2026-09-30/'
TARGET = 1_000_000


def jload(p, default=None):
    try:
        return json.load(open(p, encoding='utf-8'))
    except Exception:
        return default if default is not None else {}


summ = jload(OUT + '1M-SUMMARY.json')
qa = jload(OUT + '1M-QA-REPORT.json')
acc = jload(OUT + '1M-FAMILY-ACCEPTANCE-TEST.json')
final = summ.get('FINAL_DISTINCT_CANDIDATES', 0)

rows = []
with gzip.open(OUT + 'LIVDAR-1M-CANDIDATE-MANIFEST.csv.gz', 'rt', encoding='utf-8',
               newline='') as f:
    for r in csv.DictReader(f):
        rows.append(r)

rej = collections.Counter()
rej_class = collections.Counter()
try:
    with gzip.open(OUT + 'LIVDAR-1M-REJECTED-CANDIDATES.csv.gz', 'rt', encoding='utf-8',
                   newline='') as f:
        for r in csv.DictReader(f):
            st = (r.get('status') or '').strip() or 'REJECTED_UNLABELLED'
            rej[st] += 1
            reason = (r.get('rejection_reason') or '')
            rej_class[reason.split(':')[0][:70] or 'no reason recorded'] += 1
except Exception:
    pass

# parent geography, from the assignment the containment pass wrote
pa = collections.Counter()
pa_cls = collections.Counter()
try:
    for line in gzip.open(ROOT + 'data/atlas/sources/osm-poi/_parent-assignment.jsonl.gz', 'rt',
                          encoding='utf-8'):
        line = line.strip()
        if not line:
            continue
        o = json.loads(line)
        pa['attached'] += 1
        pa_cls[o.get('parent_cls') or '?'] += 1
except Exception:
    pass
ADMIN = {'region', 'county'}
admin_attached = sum(v for k, v in pa_cls.items() if k in ADMIN)

measurements = sorted(os.path.basename(p) for p in
                      glob.glob(ROOT + 'data/atlas/measurements/*2026-10-01*'))

def counter_table(c, head=None, label='key'):
    items = c.most_common(head) if head else sorted(c.items())
    w = max([len(str(k)) for k, _ in items] + [len(label)])
    out = [f'| {label.ljust(w)} | rows |', f'| {"-" * w} | --- |']
    for k, v in items:
        out.append(f'| {str(k).ljust(w)} | {v:,} |')
    return '\n'.join(out)


by_surface = collections.Counter(r['surface'] for r in rows)
by_market = collections.Counter(r['market'] for r in rows)
by_lang = collections.Counter(r['language'] for r in rows)
by_country = collections.Counter(r['country'] for r in rows)
by_source = collections.Counter((r['data_source'] or '')[:64] for r in rows)
by_family = collections.Counter(r['family'] for r in rows)
by_etype = collections.Counter(r['entity_type'] for r in rows)

md = []
A = md.append
A('# Livdar candidate inventory: the final report in the shape the brief asks for')
A('')
A('Generated by scripts/atlas/scale/final-brief-report.py, which reads the artifacts rather than')
A('restating them. Production untouched, nothing published, the live Atlas is still 500 pages and')
A('there is no cohort 003.')
A('')
A('## FINAL DISTINCT VALID and the gap')
A('')
A(f'| | rows |')
A(f'| --- | --- |')
A(f'| **FINAL DISTINCT VALID** | **{final:,}** |')
A(f'| target | {TARGET:,} |')
A(f'| **GAP TO 1M** | **{max(0, TARGET - final):,}** |')
A(f'| generated before any gate | {summ.get("generated_before_any_gate", 0):,} |')
A(f'| funnel reconciles | {summ.get("funnel_reconciles")} |')
A(f'| distinct families | {summ.get("distinct_families", 0):,} |')
A(f'| markets | {len(by_market)} |')
A('')
A('Every removal, as the funnel records it. Generated minus this column equals the final count,')
A('checked by a verifier that fails the run rather than by reading the numbers.')
A('')
removals = {k: v for k, v in summ.items() if k.startswith('removed_') and isinstance(v, int)}
A(counter_table(collections.Counter(removals), label='removal stage'))
A('')
A('## BY SURFACE')
A('')
A(counter_table(by_surface, label='surface'))
A('')
A('## BY LOCALE and BY COUNTRY')
A('')
A(counter_table(by_market, label='market'))
A('')
A(counter_table(by_lang, label='language'))
A('')
A('Top 20 destination countries, which are NOT the same thing as the markets above: the searcher')
A('market and the place a page is about are different axes and the brief is explicit about that.')
A('')
A(counter_table(by_country, head=20, label='destination country'))
A('')
A('## BY SOURCE')
A('')
A(counter_table(by_source, label='data source and licence'))
A('')
A('## BY ENTITY TYPE')
A('')
A(counter_table(by_etype, label='entity type'))
A('')
A('## BY FAMILY, the 40 largest')
A('')
A(counter_table(by_family, head=40, label='family'))
A('')
A(f'{len(by_family):,} families in total. The full list with the content contract per family is in')
A('1M-UNIQUE-CONTENT-CONTRACT.csv and the per-condition verdicts in 1M-FAMILY-ACCEPTANCE-TEST.json.')
A('')
A('## CONTENT QUALITY: what was rejected and why')
A('')
A(counter_table(rej, label='rejection status'))
A('')
A('The reason text, grouped by its first clause:')
A('')
A(counter_table(rej_class, head=25, label='recorded reason'))
A('')
A('## QA: every check in the pass')
A('')
checks = qa.get('checks', {})
A(counter_table(collections.Counter(checks), label='check'))
A('')
A('## FAMILY ACCEPTANCE TEST, ten conditions')
A('')
A(counter_table(collections.Counter(acc.get('verdicts', {})), label='verdict'))
A('')
A(counter_table(collections.Counter(acc.get('pages_by_verdict', {})), label='pages by verdict'))
A('')
fails = acc.get('most_common_failed_condition', {})
A('Failed conditions across all families: '
  + (', '.join(f'{k} ({v})' for k, v in fails.items()) if fails else 'none'))
A('')
A('## PARENT GEOGRAPHY')
A('')
if pa['attached']:
    A(f'POI attached to a containment parent: {pa["attached"]:,}')
    A('')
    A(counter_table(pa_cls, head=20, label='parent class'))
    A('')
    A(f'Of those attachments, {admin_attached:,} are to a region or a county, which contains every')
    A('point in its country by construction. The honest outdoor attachment is the remainder,')
    A(f'{pa["attached"] - admin_attached:,}. A rate that counts administrative containment is')
    A('measuring geometry rather than attribution, and this report does not quote one.')
else:
    A('No parent assignment on disk.')
A('')
A('## MEASUREMENTS TAKEN IN THIS PASS')
A('')
A('Each of these is a file in data/atlas/measurements, with the question it answered, the units it')
A('cost where it used Ahrefs, and the decision it drove.')
A('')
for m in measurements:
    A(f'- {m}')
A('')
A('## NEW SOURCES THIS PASS, AND WHAT EACH ONE OPENS')
A('')
reg = jload(ROOT + 'data/atlas/measurements/new-source-register-2026-10-02-second-pass.json', {})
srcs = reg.get('sources') or []
if srcs:
    A('| source | licence | status | what it opens |')
    A('| --- | --- | --- | --- |')
    for sc in srcs:
        lic = sc.get('licence') or (', '.join(sc.get('licences') or []) or 'see the register')
        A(f'| {sc.get("name","")} | {lic} | {sc.get("status_today") or sc.get("reclassified") or ""} '
          f'| {(sc.get("families_opened") or sc.get("what_they_are_worth") or "")[:160]} |')
    A('')
    corr = reg.get('the_correction_this_pass_makes_to_the_first')
    if corr:
        A('One estimate was withdrawn rather than quietly dropped:')
        A('')
        A(corr)
        A('')
else:
    A('No source register on disk for this pass.')
A('')
A('## SCALE PATHS: COUNTED AGAINST PROJECTED')
A('')
arith = reg.get('where_this_leaves_the_arithmetic') or {}
if arith:
    A(f'Counted today in the manifest: **{final:,}**')
    A('')
    A('Paths with a COUNTED entity-level number:')
    A('')
    for k, v in (arith.get('paths_with_a_counted_entity_level_number') or {}).items():
        A(f'- {k.replace("_", " ")}: {v}')
    A('')
    A('Paths whose number is PROJECTED, with what it is projected from stated in the register:')
    A('')
    for k, v in (arith.get('paths_projected') or {}).items():
        A(f'- {k.replace("_", " ")}: {v}')
    A('')
    st = arith.get('the_honest_statement')
    if st:
        A(st)
else:
    A('No scale-path arithmetic on disk for this pass.')
A('')
A('## THE DESTINATION AXIS')
A('')
A('Before this pass, 99.97 per cent of the inventory was about the same eleven countries the')
A('eleven searcher markets live in, which is backwards for a travel-connectivity product: the')
A('commercial moment is a person in one country about to travel to another. The axis was not')
A('opened by relaxing a gate. markets_for() already asks for evidence rather than for a country')
A('list, so the work was to supply the evidence it asks for, in two halves that are both required:')
A('')
A('1. the destination country carries measured demand in the page language, where BOTH a')
A('   connectivity keyword and a travel-information keyword clear the floor')
A('2. the place itself carries a mark in that same language, a Wikipedia article or a GeoNames')
A('   alternate name, which is a PROXY for interest and is labelled a proxy on every row that')
A('   rests on it')
A('')
# Counted the same way the QA counts it, from the market's home country and the row's country,
# not from a substring of market_demand_evidence: that column holds a coarse token
# (shape_measured, measured_in_this_market) and never the destination sentence, so the
# substring test reported a flat zero on an inventory holding 16,165 of them.
HOME_OF = dict(entity_identity.MKT_COUNTRY)
COUNTRY_ENTITY_TYPES = {'country', 'country-pair'}
dest = [r for r in rows
        if (r.get('country') or '').strip()
        and (r.get('entity_type') or '') not in COUNTRY_ENTITY_TYPES
        and HOME_OF.get(r.get('market')) != (r.get('country') or '').strip()]
dest_rows = len(dest)
A(f'Pages about a country that is not their own market\'s country: {dest_rows:,}')
A('')
A('| market | destination pages |')
A('| --- | --- |')
for m, n in collections.Counter(r.get('market') for r in dest).most_common():
    A(f'| {m} | {n:,} |')
A('')
dbasis = collections.Counter(
    'home market' if ' is the HOME market' in (r.get('same_language_ownership_basis') or '')
    else 'measured searching this entity itself'
    if 'measured searching for this entity itself' in (r.get('same_language_ownership_basis') or '')
    else 'family-level score, the weakest basis'
    if 'the family-level score decides' in (r.get('same_language_ownership_basis') or '')
    else 'the only market serving this language that earns the entity'
    for r in dest)
A('How those pages earned the market that owns them:')
A('')
A('| ownership basis | pages |')
A('| --- | --- |')
for b, n in dbasis.most_common():
    A(f'| {b} | {n:,} |')
A('')
A('And the largest lever examined in this pass did NOT open. Once the city pool grew, the biggest')
A('gate in the funnel became the measured-tier cap. It was sampled rather than argued, 28 cities')
A('in two languages, and the cap stands: the family phrasing is dead at that depth, with')
A('"estoril cosa vedere" at 30 against "estoril" at 2,300. A name with volume is not a page')
A('intent. The full measurement is in tier-cap-vs-destination-mark-2026-10-02.json.')

# ---- the sections the 2026-10-06 brief asks for by name ---------------------------------------
# Each one reads a measurement file rather than restating a number, so the report cannot drift
# from the evidence and a missing file shows as missing rather than as a confident zero.
MEAS = ROOT + 'data/atlas/measurements/'


def m(fn):
    return jload(MEAS + fn, {})


A('')
A('## COUNTRIES')
A('')
_cc = collections.Counter(r['country'] for r in rows if (r.get('country') or '').strip())
_dest_tab = (m('destination-demand-by-country-language-six-languages-2026-10-06.json')
             .get('table') or {})
_qual = {k.split('|')[0] for k, v in _dest_tab.items() if v.get('qualifies')}
for fn in ('destination-demand-by-country-language-2026-10-02.json',
           'destination-demand-by-country-language-tr-2026-10-05.json',
           'destination-demand-by-country-language-ko-2026-10-05.json'):
    for pair in (m(fn).get('qualifying_pairs') or []):
        _qual.add(pair.split('|')[0])
_mirror = m('destination-mirror-coverage-2026-10-02.json')
_blocked = set(_mirror.get('not_carried_by_this_mirror') or [])
A('| | count |')
A('| --- | --- |')
A(f'| destination countries represented by at least one page | {len(_cc):,} |')
A(f'| countries whose demand qualifies in at least one language | {len(_qual):,} |')
A(f'| of those, represented by a page today | {len(_qual & set(_cc)):,} |')
A(f'| of those, measured as qualifying and NOT yet represented | {len(_qual - set(_cc)):,} |')
A(f'| countries this OSM mirror does not carry, so blocked on a second source '
  f'| {len(_blocked):,} |')
A('')
A('Countries that qualify on demand and have no page yet, which is the queue in priority order '
  'rather than a gap:')
A('')
A('  ' + ' '.join(sorted(_qual - set(_cc))) or '  none')
A('')
if _blocked:
    A('Blocked on the mirror, recorded with what each is worth in '
      'destination-mirror-coverage-2026-10-02.json:')
    A('')
    A('  ' + ' '.join(sorted(_blocked)))
    A('')

A('## MARKETS')
A('')
_active = sorted({r['market'] for r in rows})
A(f'Active and generating: {len(_active)}')
A('')
A('  ' + ' '.join(_active))
A('')
_rank06 = m('market-expansion-ranking-2026-10-06.json').get('candidates') or []
_rank05 = m('market-expansion-ranking-2026-10-05.json').get('candidates') or []
A(f'Researched as candidates and NOT admitted: {len(_rank05) + len(_rank06)} across two passes.')
A('')
A('| candidate | new language | measured volume | highest CPC cents | disposition |')
A('| --- | --- | --- | --- | --- |')
for c in _rank06:
    pr = c.get('priority')
    disp = f'recommended, priority {pr}' if isinstance(pr, int) else str(pr)
    A(f"| {c['market']} | {'yes' if c.get('is_a_new_language') else 'no'} "
      f"| {c.get('total_measured_volume', 0):,} | {c.get('highest_cpc_cents', 0)} | {disp} |")
A('')
A('The rule both passes found, and it is the best predictor of page yield measured anywhere in '
  'this project: a candidate whose per-city family is ALIVE yields a page per city, and a '
  'candidate where only the generic connectivity intent lives yields none. Czech reads esim '
  '10,000 and then praha co videt NINETY; Arabic in the UAE reads esim 5,300 and then Paris 10. '
  'Both are refused on that basis, and ko-KR stays out on its SERP after passing demand by the '
  'widest margin of any candidate.')
A('')

A('## LANGUAGES')
A('')
_lang_now = collections.Counter(r['language'] for r in rows)
A('| language | pages | destination gate measured |')
A('| --- | --- | --- |')
_six = set((m('destination-demand-by-country-language-six-languages-2026-10-06.json')
            .get('per_language') or {}))
_old_langs = set()
for fn in ('destination-demand-by-country-language-2026-10-02.json',
           'destination-demand-by-country-language-tr-2026-10-05.json',
           'destination-demand-by-country-language-ko-2026-10-05.json'):
    for pair in (m(fn).get('qualifying_pairs') or []):
        _old_langs.add(pair.split('|')[1])
for lg, n in _lang_now.most_common():
    when = ('2026-10-06, newly measured' if lg in _six
            else 'earlier passes' if lg in _old_langs else 'NOT MEASURED')
    A(f'| {lg} | {n:,} | {when} |')
A('')

A('## OUTDOOR: individual entity against aggregation')
A('')
_thin = m('thin-entity-pages-2026-10-06.json')
_ind = sum(n for f, n in by_family.items() if f.startswith('outdoors.'))
A('| | count |')
A('| --- | --- |')
A(f'| outdoor pages in the manifest | {_ind:,} |')
if _thin:
    A(f'| pages that carried exactly one measured attribute before the gate '
      f'| {_thin.get("rows_with_exactly_one_measured_attribute", 0):,} |')
    A(f'| of those, sharing a name with a sibling in the same market '
      f'| {_thin.get("rows_with_one_attribute_and_a_name_shared_in_the_same_market", 0):,} |')
A('')
A('The gate: an individual outdoor entity page needs two or more measured attributes OR its own '
  'Wikipedia article in the page language. A Wikidata item alone is not enough, because it '
  'admits "45 Hill" alongside the Zugspitze. Every refused feature goes to its parent list WITH '
  'its facts, so a rejected peak still appears as a named row with its elevation. The counts for '
  'the current build are printed by outdoor-feature-candidates.py and outdoor-aggregations.py '
  'and are carried in the run log rather than retyped here.')
A('')

A('## TRAILS')
A('')
_tr = {f: n for f, n in by_family.items() if 'trail' in f}
if _tr:
    A('| family | pages |')
    A('| --- | --- |')
    for f, n in sorted(_tr.items(), key=lambda x: -x[1]):
        A(f'| {f} | {n:,} |')
    A(f'| **total** | **{sum(_tr.values()):,}** |')
A('')

A('## TOOLS, counted apart from the page target on purpose')
A('')
_tool = m('tool-family-demand-2026-10-06.json')
if _tool:
    for mkt, heads in (_tool.get('the_heads') or {}).items():
        A(f'{mkt}:')
        A('')
        A('| keyword | volume | difficulty | CPC cents |')
        A('| --- | --- | --- | --- |')
        for k, v in sorted(heads.items(), key=lambda x: -x[1].get('volume', 0)):
            A(f"| {k} | {v.get('volume', 0):,} | {v.get('kd')} | {v.get('cpc_cents')} |")
        A('')
    A('A tool family is about twenty pages per market, so the whole surface is a few hundred '
      'pages against a target of a million, while brutto netto rechner alone carries more '
      'measured monthly demand than this entire inventory. The two numbers are not added '
      'together anywhere in this report, because adding them would hide both facts. The '
      'city-scoped form of a calculator was measured and does not exist as an intent: salary '
      'needed to live in london reads TWENTY.')
    A('')

A('## AHREFS')
A('')
_units = 0
for fn in sorted(glob.glob(MEAS + '*2026-10-06*.json')):
    d = jload(fn, {})
    # licence_and_provenance is a string in some files and a dict in others, so the lookup has
    # to tolerate both rather than assume the shape of a file written on another day.
    lp = d.get('licence_and_provenance')
    u = d.get('units_spent')
    if u is None and isinstance(lp, dict):
        u = lp.get('units_spent')
    if isinstance(u, int):
        _units += u
A(f'Units spent on 2026-10-06 measurements, summed from the files themselves: {_units:,}')
A('')
A('| module used | what it settled |')
A('| --- | --- |')
A('| Keywords Explorer overview | the destination gate in six unmeasured languages, eight '
  'candidate markets, the 96 category tokens, the climate family, the tool heads, the French '
  'property tail, the education family |')
A('| SERP overview | prix immobilier angers and prix m2 auch, both PLATFORM_DOMINATED |')
A('| Site Explorer metrics and top pages | mapcarta, weatherspark, weather-and-climate and '
  'climatestotravel |')
A('')

A('## PUBLICATION')
A('')
A('| | |')
A('| --- | --- |')
A('| mass publish | NO |')
A('| cohort 003 | NO |')
A('| production changed | NO |')
A('| routing changed | NO |')
A('| sitemap changed for this inventory | NO |')
A('| indexing requested | NO |')
A('')

A('## REPO')
A('')
A('| | |')
A('| --- | --- |')
A('| branch | claude/seo-handoff-partial-data-7rs7zi |')
A('| manifest | reports/livdar-expiry-freeze-2026-09-30/LIVDAR-1M-CANDIDATE-MANIFEST.csv.gz |')
A('| parquet | reports/livdar-expiry-freeze-2026-09-30/LIVDAR-1M-CANDIDATE-MANIFEST.parquet |')
A('| rejected set | reports/livdar-expiry-freeze-2026-09-30/1M-REJECTED-CANDIDATES.csv.gz |')
A('| measurements | data/atlas/measurements/ |')
A('| rebuild | ./scripts/atlas/scale/run-1m-pipeline.sh |')
A('| resume after the aggregation | ./scripts/atlas/scale/run-1m-pipeline.sh --from-aggregations |')
A('| resume at the manifest | ./scripts/atlas/scale/run-1m-pipeline.sh --from-manifest |')
A('')

with open(OUT + '1M-BRIEF-FINAL-REPORT.md', 'w', encoding='utf-8') as f:
    f.write('\n'.join(md) + '\n')
print(f'written {OUT}1M-BRIEF-FINAL-REPORT.md  ({sum(str(x).count(chr(10)) + 1 for x in md):,} lines)')
print(f'FINAL {final:,}  gap {max(0, TARGET - final):,}  families {len(by_family)}')
