#!/usr/bin/env python3
"""
The final report in the shape the brief asks for, assembled from the artifacts rather than retyped.

Every number here is read from a file another script wrote and verified: the manifest, the summary,
the QA report, the acceptance test, the rejected set, the parent assignment and the measurement
files in data/atlas/measurements. Nothing is entered by hand, so the report cannot drift from the
inventory the way a report typed from memory does.

Usage: final-brief-report.py
Writes reports/livdar-expiry-freeze-2026-09-30/1M-BRIEF-FINAL-REPORT.md
"""
import collections, csv, glob, gzip, json, os, sys

ROOT = '/home/user/Livdar-eSim/'
OUT = ROOT + 'reports/livdar-expiry-freeze-2026-09-30/'
TARGET = 1_000_000


def jload(p, default=None):
    try:
        return json.load(open(p, encoding='utf-8'))
    except Exception:
        return default if default is not None else {}


summ = jload(OUT + '1M-SUMMARY.json')
qa = jload(OUT + '1M-QA-REPORT.json')
acc = jload(OUT + '1M-FAMILY-ACCEPTANCE-TEST.json')
final = summ.get('FINAL_DISTINCT_CANDIDATES', 0)

rows = []
with gzip.open(OUT + 'LIVDAR-1M-CANDIDATE-MANIFEST.csv.gz', 'rt', encoding='utf-8',
               newline='') as f:
    for r in csv.DictReader(f):
        rows.append(r)

rej = collections.Counter()
rej_class = collections.Counter()
try:
    with gzip.open(OUT + 'LIVDAR-1M-REJECTED-CANDIDATES.csv.gz', 'rt', encoding='utf-8',
                   newline='') as f:
        for r in csv.DictReader(f):
            st = (r.get('status') or '').strip() or 'REJECTED_UNLABELLED'
            rej[st] += 1
            reason = (r.get('rejection_reason') or '')
            rej_class[reason.split(':')[0][:70] or 'no reason recorded'] += 1
except Exception:
    pass

# parent geography, from the assignment the containment pass wrote
pa = collections.Counter()
pa_cls = collections.Counter()
try:
    for line in gzip.open(ROOT + 'data/atlas/sources/osm-poi/_parent-assignment.jsonl.gz', 'rt',
                          encoding='utf-8'):
        line = line.strip()
        if not line:
            continue
        o = json.loads(line)
        pa['attached'] += 1
        pa_cls[o.get('parent_cls') or '?'] += 1
except Exception:
    pass
ADMIN = {'region', 'county'}
admin_attached = sum(v for k, v in pa_cls.items() if k in ADMIN)

measurements = sorted(os.path.basename(p) for p in
                      glob.glob(ROOT + 'data/atlas/measurements/*2026-10-01*'))

def counter_table(c, head=None, label='key'):
    items = c.most_common(head) if head else sorted(c.items())
    w = max([len(str(k)) for k, _ in items] + [len(label)])
    out = [f'| {label.ljust(w)} | rows |', f'| {"-" * w} | --- |']
    for k, v in items:
        out.append(f'| {str(k).ljust(w)} | {v:,} |')
    return '\n'.join(out)


by_surface = collections.Counter(r['surface'] for r in rows)
by_market = collections.Counter(r['market'] for r in rows)
by_lang = collections.Counter(r['language'] for r in rows)
by_country = collections.Counter(r['country'] for r in rows)
by_source = collections.Counter((r['data_source'] or '')[:64] for r in rows)
by_family = collections.Counter(r['family'] for r in rows)
by_etype = collections.Counter(r['entity_type'] for r in rows)

md = []
A = md.append
A('# Livdar candidate inventory: the final report in the shape the brief asks for')
A('')
A('Generated by scripts/atlas/scale/final-brief-report.py, which reads the artifacts rather than')
A('restating them. Production untouched, nothing published, the live Atlas is still 500 pages and')
A('there is no cohort 003.')
A('')
A('## FINAL DISTINCT VALID and the gap')
A('')
A(f'| | rows |')
A(f'| --- | --- |')
A(f'| **FINAL DISTINCT VALID** | **{final:,}** |')
A(f'| target | {TARGET:,} |')
A(f'| **GAP TO 1M** | **{max(0, TARGET - final):,}** |')
A(f'| generated before any gate | {summ.get("generated_before_any_gate", 0):,} |')
A(f'| funnel reconciles | {summ.get("funnel_reconciles")} |')
A(f'| distinct families | {summ.get("distinct_families", 0):,} |')
A(f'| markets | {len(by_market)} |')
A('')
A('Every removal, as the funnel records it. Generated minus this column equals the final count,')
A('checked by a verifier that fails the run rather than by reading the numbers.')
A('')
removals = {k: v for k, v in summ.items() if k.startswith('removed_') and isinstance(v, int)}
A(counter_table(collections.Counter(removals), label='removal stage'))
A('')
A('## BY SURFACE')
A('')
A(counter_table(by_surface, label='surface'))
A('')
A('## BY LOCALE and BY COUNTRY')
A('')
A(counter_table(by_market, label='market'))
A('')
A(counter_table(by_lang, label='language'))
A('')
A('Top 20 destination countries, which are NOT the same thing as the markets above: the searcher')
A('market and the place a page is about are different axes and the brief is explicit about that.')
A('')
A(counter_table(by_country, head=20, label='destination country'))
A('')
A('## BY SOURCE')
A('')
A(counter_table(by_source, label='data source and licence'))
A('')
A('## BY ENTITY TYPE')
A('')
A(counter_table(by_etype, label='entity type'))
A('')
A('## BY FAMILY, the 40 largest')
A('')
A(counter_table(by_family, head=40, label='family'))
A('')
A(f'{len(by_family):,} families in total. The full list with the content contract per family is in')
A('1M-UNIQUE-CONTENT-CONTRACT.csv and the per-condition verdicts in 1M-FAMILY-ACCEPTANCE-TEST.json.')
A('')
A('## CONTENT QUALITY: what was rejected and why')
A('')
A(counter_table(rej, label='rejection status'))
A('')
A('The reason text, grouped by its first clause:')
A('')
A(counter_table(rej_class, head=25, label='recorded reason'))
A('')
A('## QA: every check in the pass')
A('')
checks = qa.get('checks', {})
A(counter_table(collections.Counter(checks), label='check'))
A('')
A('## FAMILY ACCEPTANCE TEST, ten conditions')
A('')
A(counter_table(collections.Counter(acc.get('verdicts', {})), label='verdict'))
A('')
A(counter_table(collections.Counter(acc.get('pages_by_verdict', {})), label='pages by verdict'))
A('')
fails = acc.get('most_common_failed_condition', {})
A('Failed conditions across all families: '
  + (', '.join(f'{k} ({v})' for k, v in fails.items()) if fails else 'none'))
A('')
A('## PARENT GEOGRAPHY')
A('')
if pa['attached']:
    A(f'POI attached to a containment parent: {pa["attached"]:,}')
    A('')
    A(counter_table(pa_cls, head=20, label='parent class'))
    A('')
    A(f'Of those attachments, {admin_attached:,} are to a region or a county, which contains every')
    A('point in its country by construction. The honest outdoor attachment is the remainder,')
    A(f'{pa["attached"] - admin_attached:,}. A rate that counts administrative containment is')
    A('measuring geometry rather than attribution, and this report does not quote one.')
else:
    A('No parent assignment on disk.')
A('')
A('## MEASUREMENTS TAKEN IN THIS PASS')
A('')
A('Each of these is a file in data/atlas/measurements, with the question it answered, the units it')
A('cost where it used Ahrefs, and the decision it drove.')
A('')
for m in measurements:
    A(f'- {m}')
A('')
A('## WHAT THE ARITHMETIC SAYS')
A('')
A('The full argument, with every path sized and every refusal explained, is in')
A('1M-DISCOVERY-AND-SCALE-REPORT.md. The short form: the defensible ceiling with every path')
A('measured in this pass built out is 405,000 to 540,000, and reaching one million would require')
A('relaxing a quality gate, translating without local evidence, or a new entity axis of roughly')
A('450,000 real entities carrying distinct data and demand. The first two are refused by the brief')
A('and by this pipeline. The third has one measured candidate, the outdoor feature layer, and it is')
A('worth a quarter of what would be needed.')

with open(OUT + '1M-BRIEF-FINAL-REPORT.md', 'w', encoding='utf-8') as f:
    f.write('\n'.join(md) + '\n')
print(f'written {OUT}1M-BRIEF-FINAL-REPORT.md  ({len(md)} lines)')
print(f'FINAL {final:,}  gap {max(0, TARGET - final):,}  families {len(by_family)}')
