#!/usr/bin/env python3
"""
Do the artifacts agree with each other?

Every number in the deliverable is read from a generated file, but each file is generated by
a different script, and a disagreement between two of them is the failure mode that is
hardest to notice and most damaging to trust. It has already happened twice in this project:
a parquet write failed after the manifest had been written and before the summary was
computed, so the manifest held 242,996 while the summary read 164,656; and the partition
tree kept three rows from an earlier run, so counting across the tree gave a different total
from the manifest it was built from.

This script asserts agreement instead of hoping for it. It is the last step, it reads only
what the other scripts wrote, and it exits non-zero on any mismatch, so a disagreement stops
the pipeline rather than reaching a report.
"""
import csv, gzip, json, os, sys, glob, collections

ROOT = '/home/user/Livdar-eSim/'
OUT = ROOT + 'reports/livdar-expiry-freeze-2026-09-30/'
PART = ROOT + 'data/atlas/candidates/'

problems = []
facts = {}


def note(name, value):
    facts[name] = value
    return value


# 1. the manifest itself, which is the authority every other number has to match
with gzip.open(OUT + 'LIVDAR-1M-CANDIDATE-MANIFEST.csv.gz', 'rt', encoding='utf-8',
               newline='') as f:
    man = list(csv.DictReader(f))
note('manifest_rows', len(man))
note('manifest_distinct_urls', len({r['url_pattern'] for r in man}))
if facts['manifest_rows'] != facts['manifest_distinct_urls']:
    problems.append(f"the manifest has {facts['manifest_rows']:,} rows but only "
                    f"{facts['manifest_distinct_urls']:,} distinct URLs, so a URL is "
                    f"claimed by more than one row")

# 2. the summary
summ = json.load(open(OUT + '1M-SUMMARY.json'))
note('summary_final', summ['FINAL_DISTINCT_CANDIDATES'])
if summ['FINAL_DISTINCT_CANDIDATES'] != len(man):
    problems.append(f"1M-SUMMARY.json says {summ['FINAL_DISTINCT_CANDIDATES']:,} final "
                    f"candidates and the manifest holds {len(man):,}")

# the funnel has to be monotonic: no stage may keep more than the one before it
funnel = [('raw_candidate_combinations', summ.get('raw_candidate_combinations')),
          ('after_exact_dedupe', summ.get('after_exact_dedupe')),
          ('after_semantic_dedupe', summ.get('after_semantic_dedupe')),
          ('after_localization_and_cross_locale_gate',
           summ.get('after_localization_and_cross_locale_gate')),
          ('after_cannibalization_filtering', summ.get('after_cannibalization_filtering')),
          ('FINAL_DISTINCT_CANDIDATES', summ.get('FINAL_DISTINCT_CANDIDATES'))]
seq = [(n, v) for n, v in funnel if isinstance(v, int)]
for (n1, v1), (n2, v2) in zip(seq, seq[1:]):
    if v2 > v1:
        problems.append(f"the funnel grows at {n2}: {v1:,} before it and {v2:,} after, which "
                        f"a filter cannot do")
note('funnel', {n: v for n, v in seq})

# 2b. the funnel has to SUM, not merely shrink. Monotonicity alone passed a funnel in which
# 2,855 rows disappeared at exact dedupe with no record anywhere: every stage was smaller
# than the one before it and the inventory was still short by rows nobody could account for.
# Generated minus every recorded removal must equal the final count, which also means every
# removal has to be written down somewhere to be subtracted.
gen = summ.get('generated_before_any_gate')
if isinstance(gen, int):
    removals = (summ.get('removed_by_uniqueness_and_serp_gate', 0)
                + summ.get('removed_as_exact_duplicate_urls', 0)
                + summ.get('removed_by_localisation_gate', 0))
    note('generated_before_any_gate', gen)
    note('total_recorded_removals', removals)
    if gen - removals != summ['FINAL_DISTINCT_CANDIDATES']:
        problems.append(
            f"the funnel does not sum: {gen:,} generated minus {removals:,} recorded "
            f"removals is {gen - removals:,}, but the final count is "
            f"{summ['FINAL_DISTINCT_CANDIDATES']:,}. The difference is rows that left the "
            f"pipeline without a record, which is what hid the URL collision.")
    if summ.get('funnel_reconciles') is False:
        problems.append('the manifest itself reports funnel_reconciles false')
    # and the rejected file must hold exactly the removals that are supposed to be preserved
    preserved = (summ.get('removed_by_uniqueness_and_serp_gate', 0)
                 + summ.get('removed_as_exact_duplicate_urls', 0)
                 + summ.get('removed_by_localisation_gate', 0))
    note('removals_that_should_be_preserved', preserved)

# 3. the QA report
qa = json.load(open(OUT + '1M-QA-REPORT.json'))
note('qa_rows', qa['manifest_rows'])
if qa['manifest_rows'] != len(man):
    problems.append(f"1M-QA-REPORT.json read {qa['manifest_rows']:,} rows and the manifest "
                    f"holds {len(man):,}; the QA ran against a different manifest")

# 4. the gap summary
gap = json.load(open(OUT + '1M-GAP-SUMMARY.json'))
note('gap_built', gap['built'])
if gap['built'] != len(man):
    problems.append(f"1M-GAP-SUMMARY.json counts {gap['built']:,} built and the manifest "
                    f"holds {len(man):,}")
if gap['built'] + gap['gap'] != gap['target']:
    problems.append(f"the gap does not close: built {gap['built']:,} plus gap "
                    f"{gap['gap']:,} is not the target {gap['target']:,}")

# 5. the partition tree, counted along every axis independently
idx = json.load(open(PART + '_index.json'))
for axis, parts in idx['partitions'].items():
    total = sum(p['rows'] for p in parts.values())
    note(f'partition_rows_{axis}', total)
    if total != len(man):
        problems.append(f"the {axis} partitions hold {total:,} rows in total and the "
                        f"manifest holds {len(man):,}")
# and counted from the files on disk rather than from the index that describes them
on_disk = 0
for f in sorted(glob.glob(PART + 'market=*/candidates.jsonl.gz')):
    with gzip.open(f, 'rt', encoding='utf-8') as fh:
        on_disk += sum(1 for _ in fh)
note('partition_rows_on_disk_market_axis', on_disk)
if on_disk != len(man):
    problems.append(f"the market partition FILES hold {on_disk:,} rows and the manifest "
                    f"holds {len(man):,}; the index may describe a tree that is not there")

# 6. rejections. Every row generated is either kept or rejected, and nothing is both.
with gzip.open(OUT + 'LIVDAR-1M-REJECTED-CANDIDATES.csv.gz', 'rt', encoding='utf-8',
               newline='') as f:
    rej = list(csv.DictReader(f))
note('rejected_rows', len(rej))
kept_urls = {r['url_pattern'] for r in man}
# A REJECTED_DUPLICATE row shares its URL with the row that claimed it first; that is what
# the rejection MEANS, so those are exempt. Every other rejection sharing a URL with a kept
# page is the symptom that found the five-family path collision in this pass, so the check
# stays sharp for them.
both = kept_urls & {r['url_pattern'] for r in rej
                    if not (r.get('rejection_reason') or '').startswith('REJECTED_DUPLICATE')}
if both:
    problems.append(f"{len(both):,} URLs appear in both the manifest and the rejected file "
                    f"without being duplicate-URL rejections, for example "
                    f"{sorted(both)[0]}; two different families are claiming one path")
if isinstance(gen, int) and len(rej) != facts.get('removals_that_should_be_preserved'):
    problems.append(f"the rejected file holds {len(rej):,} rows but the funnel records "
                    f"{facts.get('removals_that_should_be_preserved'):,} removals that are "
                    f"supposed to be preserved; the difference was dropped without a record")
no_reason = [r for r in rej if not (r.get('rejection_reason') or '').strip()]
if no_reason:
    problems.append(f"{len(no_reason):,} rejected rows carry no rejection_reason, so the "
                    f"rejection cannot be audited or appealed")

# 7. every kept row must carry a localisation verdict, and it must be a keeping one
bad = collections.Counter()
for r in man:
    c = (r.get('localization_class') or '').strip()
    if c not in ('NATIVE_LOCALE', 'VALID_LOCALIZATION'):
        bad[c or '(none)'] += 1
if bad:
    problems.append(f"kept rows carrying a localisation class that should have rejected "
                    f"them, or none at all: {dict(bad)}")

print(json.dumps(facts, indent=1))
if problems:
    print('\nARTIFACTS DO NOT AGREE:', file=sys.stderr)
    for p in problems:
        print('  - ' + p, file=sys.stderr)
    sys.exit(1)
print('\nevery artifact agrees: manifest, summary, QA, gap summary, all four partition axes, '
      'the partition files themselves, and the rejected set.')
