#!/bin/bash
# Capture every geographic layer for the countries that need one, in
# PRIORITY_SCORE order: 45 per cent commercial value, 35 per cent scale, 10
# per cent measured demand, 10 per cent data readiness. Generated by
# scripts/atlas/ingest/write-priority-queue.py from
# data/atlas/measurements/capture-queue-by-priority-2026-10-06.json. Do not
# hand edit: change the matrix and regenerate.
#
# WHAT THIS QUEUE IS WORTH, measured before it was reordered:
#
#   Sixteen destination countries carry four or five OSM layers on disk.
#   Between them they produce ZERO pages whose data_source is OpenStreetMap.
#   All 268,456 OSM-sourced pages in the 401,393 manifest are about one of
#   the fourteen home-market countries. The destination POI fan-out produced
#   292,613 raw rows and the localisation gate removed 263,742 of them as
#   TRANSLATION_ONLY, which is the gate working as specified.
#
#   So an extract for a destination country buys nothing today. The queue is
#   still run because the layers are the prerequisite for any destination
#   family that later earns an information-gain basis, and because the home
#   markets in it DO convert an extract into pages. It is not the path to a
#   million, and the previous order, which put India first on a projected
#   70,165 net new, was an artifact of a blended 11.72 pages-per-city
#   benchmark that was 93 per cent home-market output.
#
# The order below, with each country tier, priority score and the net new
# valid pages the matrix expects from work on it (capture or otherwise):
#
#   DE  tier A  priority  72.5  net new      0  HOME MARKET
#   IT  tier A  priority  70.3  net new  2,917  HOME MARKET
#   CA  tier A  priority  64.0  net new      0  destination
#   AE  tier A  priority  63.9  net new      0  destination
#   EG  tier A  priority  61.2  net new      0  destination
#   IN  tier A  priority  60.7  net new  4,249  destination
#   MA  tier A  priority  60.2  net new      0  destination
#   NO  tier A  priority  58.9  net new      0  destination
#   CR  tier B  priority  50.3  net new     18  destination
#   FI  tier B  priority  50.1  net new      0  destination
#   KH  tier C  priority  48.0  net new      0  destination
#   CZ  tier B  priority  47.1  net new     33  destination
#   AR  tier C  priority  44.7  net new      0  destination
#   RO  tier B  priority  42.0  net new     38  destination
#   CL  tier C  priority  41.1  net new      0  destination
#   UA  tier C  priority  40.7  net new      0  destination
#   TN  tier C  priority  40.4  net new      0  destination
#   DO  tier D  priority  39.8  net new      0  destination
#   ZA  tier C  priority  39.5  net new      0  destination
#   SK  tier B  priority  38.4  net new      9  destination
#   TZ  tier C  priority  30.2  net new      0  destination
#   KE  tier D  priority  29.7  net new      0  destination
#
# Wanted by the matrix and NOT in this queue, because neither the mirror
# listing nor the previous queue carries a region path for them. They are
# not forgotten and not guessed at:
#   KR TH GR VN PE CO HR IL AL NZ TW IS ME MT SI LU HK HU SA QA GE CY BG VE KZ AM OM UY EE LV EC PA UZ RS BY MU MV LT AZ MK BA LK JO JM PY MN BO GT SC HN CU SV NI NP MC
#
set -u
cd /home/user/Livdar-eSim || exit 1
QUEUE="
europe/germany:DE
europe/italy:IT
north-america/canada:CA
asia/united_arab_emirates:AE
africa/egypt:EG
asia/india:IN
africa/morocco:MA
europe/norway:NO
central-america/costa_rica:CR
europe/finland:FI
asia/cambodia:KH
europe/czech_republic:CZ
south-america/argentina:AR
europe/romania:RO
south-america/chile:CL
europe/ukraine:UA
africa/tunisia:TN
central-america/dominican_republic:DO
africa/south_africa:ZA
europe/slovakia:SK
africa/tanzania:TZ
africa/kenya:KE
"
for entry in $QUEUE; do
  REGION="${entry%%:*}"; rest="${entry#*:}"
  ISO="${rest%%:*}"; CC="${rest##*:}"   # region:tag or region:tag:country
  echo "===================================================================="
  echo "[$(date +%T)] queue: $ISO from $REGION"
  if COUNTRY="$CC" ./scripts/atlas/ingest/osm-all-layers-run.sh "$REGION" "$ISO"; then
    echo "[$(date +%T)] queue: $ISO complete"
  else
    echo "[$(date +%T)] queue: $ISO INCOMPLETE, moving on so one country cannot stall the rest"
    rm -f /tmp/parents_work/$ISO-keep.osm.pbf /tmp/parents_work/$ISO-full.osm.pbf
    rm -rf /tmp/parents_work/$ISO-keep.osm.pbf.parts /tmp/parents_work/$ISO-full.osm.pbf.parts
    rm -f /tmp/parents_work/$ISO-routes.osm.pbf /tmp/parents_work/$ISO-trails.osm.pbf
  fi
  df -h / | tail -1
done
echo "[$(date +%T)] queue finished"
