#!/usr/bin/env python3
"""
Write the capture queue in PRIORITY_SCORE order instead of raw expected page count.

This emits a NEW script rather than editing osm-destination-queue.sh, because that one was
executing when the reorder was computed and a running bash script must not be rewritten under
itself: bash reads the file incrementally. The old queue stays on disk as the record of the
order it ran in, and the new one supersedes it on the next idle window.

Region paths come from two places and never from memory: the reachable map in
destination-mirror-coverage-2026-10-02.json, which was built by listing the mirror's continent
directories, and the QUEUE block of the existing script, which carries the paths already proven
to download. A country with no path from either is listed as unreachable rather than guessed at.

Usage: write-priority-queue.py
Writes scripts/atlas/ingest/osm-priority-queue.sh
"""
import json, os, re, sys

ROOT = '/home/user/Livdar-eSim/'
Q = ROOT + 'data/atlas/measurements/capture-queue-by-priority-2026-10-06.json'
OLD = ROOT + 'scripts/atlas/ingest/osm-destination-queue.sh'
MIRROR = ROOT + 'data/atlas/measurements/destination-mirror-coverage-2026-10-02.json'
OUT = ROOT + 'scripts/atlas/ingest/osm-priority-queue.sh'

# Home markets missing a layer are the only countries where capture provably turns into pages,
# so they belong at the top and neither the mirror listing nor the old queue carried them: they
# were captured by an earlier per-country script. These three paths were probed on 2026-10-06
# with a HEAD request against the mirror rather than assumed:
#   europe/germany 200, europe/italy 200, asia/taiwan 404.
# Taiwan is therefore NOT queueable from this mirror and is recorded as unreachable, not guessed.
PROBED_2026_10_06 = {'DE': 'europe/germany', 'IT': 'europe/italy'}


def paths_from_old_script():
    """{iso tag: region path} plus {country: iso tag} from the QUEUE block already proven."""
    txt = open(OLD, encoding='utf-8').read()
    m = re.search(r'QUEUE="\n(.*?)\n"', txt, re.S)
    out = {}
    if not m:
        return out
    for line in m.group(1).split():
        if ':' not in line:
            continue
        region, rest = line.split(':', 1)
        iso = rest.split(':')[0]
        cc = rest.split(':')[-1] if rest.count(':') else iso
        out.setdefault(cc[:2].upper(), []).append((region, iso, cc))
    return out


def main():
    q = json.load(open(Q, encoding='utf-8'))
    mirror = json.load(open(MIRROR, encoding='utf-8'))
    reach = {k: v.get('region_path') for k, v in (mirror.get('reachable') or {}).items()
             if isinstance(v, dict) and v.get('region_path')}
    old = paths_from_old_script()

    entries, unreachable = [], []
    for r in q['capture_queue_by_priority']:
        cc = r['country']
        if cc in old:
            for region, iso, cntry in old[cc]:
                entries.append((r, region, iso, cntry))
            continue
        p = PROBED_2026_10_06.get(cc) or r.get('osm_region_path') or reach.get(cc)
        if p:
            entries.append((r, p, cc, cc))
        else:
            unreachable.append(r)

    lines = []
    lines.append('#!/bin/bash')
    lines.append('# Capture every geographic layer for the countries that need one, in')
    lines.append('# PRIORITY_SCORE order: 45 per cent commercial value, 35 per cent scale, 10')
    lines.append('# per cent measured demand, 10 per cent data readiness. Generated by')
    lines.append('# scripts/atlas/ingest/write-priority-queue.py from')
    lines.append('# data/atlas/measurements/capture-queue-by-priority-2026-10-06.json. Do not')
    lines.append('# hand edit: change the matrix and regenerate.')
    lines.append('#')
    lines.append('# WHAT THIS QUEUE IS WORTH, measured before it was reordered:')
    lines.append('#')
    lines.append('#   Sixteen destination countries carry four or five OSM layers on disk.')
    lines.append('#   Between them they produce ZERO pages whose data_source is OpenStreetMap.')
    lines.append('#   All 268,456 OSM-sourced pages in the 401,393 manifest are about one of')
    lines.append('#   the fourteen home-market countries. The destination POI fan-out produced')
    lines.append('#   292,613 raw rows and the localisation gate removed 263,742 of them as')
    lines.append('#   TRANSLATION_ONLY, which is the gate working as specified.')
    lines.append('#')
    lines.append('#   So an extract for a destination country buys nothing today. The queue is')
    lines.append('#   still run because the layers are the prerequisite for any destination')
    lines.append('#   family that later earns an information-gain basis, and because the home')
    lines.append('#   markets in it DO convert an extract into pages. It is not the path to a')
    lines.append('#   million, and the previous order, which put India first on a projected')
    lines.append('#   70,165 net new, was an artifact of a blended 11.72 pages-per-city')
    lines.append('#   benchmark that was 93 per cent home-market output.')
    lines.append('#')
    lines.append('# The order below, with each country tier, priority score and the net new')
    lines.append('# valid pages the matrix expects from work on it (capture or otherwise):')
    lines.append('#')
    for r, region, iso, cntry in entries[:30]:
        lines.append(f"#   {r['country']:<3} tier {r['tier']}  priority {r['priority_score']:>5.1f}  "
                     f"net new {r['expected_net_new_valid_pages']:>6,}  "
                     f"{'HOME MARKET' if r['is_home_market'] else 'destination'}")
    lines.append('#')
    if unreachable:
        lines.append('# Wanted by the matrix and NOT in this queue, because neither the mirror')
        lines.append('# listing nor the previous queue carries a region path for them. They are')
        lines.append('# not forgotten and not guessed at:')
        lines.append('#   ' + ' '.join(r['country'] for r in unreachable))
        lines.append('#')
    lines.append('set -u')
    lines.append('cd /home/user/Livdar-eSim || exit 1')
    lines.append('QUEUE="')
    for r, region, iso, cntry in entries:
        lines.append(f'{region}:{iso}' + (f':{cntry}' if cntry != iso else ''))
    lines.append('"')
    lines.append('for entry in $QUEUE; do')
    lines.append('  REGION="${entry%%:*}"; rest="${entry#*:}"')
    lines.append('  ISO="${rest%%:*}"; CC="${rest##*:}"   # region:tag or region:tag:country')
    lines.append('  echo "===================================================================="')
    lines.append('  echo "[$(date +%T)] queue: $ISO from $REGION"')
    lines.append('  if COUNTRY="$CC" ./scripts/atlas/ingest/osm-all-layers-run.sh "$REGION" "$ISO"; then')
    lines.append('    echo "[$(date +%T)] queue: $ISO complete"')
    lines.append('  else')
    lines.append('    echo "[$(date +%T)] queue: $ISO INCOMPLETE, moving on so one country cannot stall the rest"')
    lines.append('    rm -f /tmp/parents_work/$ISO-keep.osm.pbf /tmp/parents_work/$ISO-full.osm.pbf')
    lines.append('    rm -rf /tmp/parents_work/$ISO-keep.osm.pbf.parts /tmp/parents_work/$ISO-full.osm.pbf.parts')
    lines.append('    rm -f /tmp/parents_work/$ISO-routes.osm.pbf /tmp/parents_work/$ISO-trails.osm.pbf')
    lines.append('  fi')
    lines.append('  df -h / | tail -1')
    lines.append('done')
    lines.append('echo "[$(date +%T)] queue finished"')
    body = '\n'.join(lines) + '\n'
    assert '—' not in body and '–' not in body, 'dash rule'
    with open(OUT, 'w', encoding='utf-8') as fh:
        fh.write(body)
    os.chmod(OUT, 0o755)
    print(f'wrote {OUT} with {len(entries)} entries, {len(unreachable)} unreachable')
    print('first ten:', ' '.join(e[0]['country'] for e in entries[:10]))


if __name__ == '__main__':
    main()
