// Every source, in one place, with everything needed to decide about it.
//
// The programme has twenty six blocked sources and the decisions about them
// were living in a markdown report, which is the wrong place: a report goes
// stale and nothing checks it. This is the machine readable version, and the
// family gate, the tools queue and the ingest scripts all read it.
//
// A source declares what it costs, what it is allowed to do, how fast it goes
// wrong, and exactly which families it unblocks. A source with no `unlocks`
// is a source nobody needs.

export const LICENCE_CLASSES = {
  open: 'Commercial reuse and redistribution permitted, attribution required',
  'open-sharealike': 'Commercial reuse permitted, derived databases must be shared under the same terms',
  'display-only': 'May be displayed alongside a link, may not be stored or redistributed',
  contractual: 'Terms set by a commercial agreement that does not exist yet',
  'public-sector': 'Government publication, reusable, terms differ per country',
  unknown: 'Not yet read',
};

export const STATES = ['built', 'partial', 'not-built', 'refused'];

const s = (x) => x;

export const SOURCES = {
  'cost-of-living-verified': s({
    id: 'cost-of-living-verified',
    provider: 'Eurostat and the World Bank',
    dataset: 'prc_ppp_ind plus PA.NUS.PPP over PA.NUS.FCRF',
    access: 'bulk JSON over HTTP, no key',
    licence: 'open',
    attribution: 'Source: Eurostat, prc_ppp_ind. World Bank, International Comparison Program, CC BY 4.0.',
    commercialReuse: true,
    storageRights: true,
    freshnessClass: 'prices',
    refreshInterval: 'annual, with the inflation series quarterly',
    cost: 0,
    rateLimits: 'none that matter at this volume',
    coverage: 'COUNTRY_READY, 199 countries. 36 with the full twelve category basket, 3 with the headline only, 160 with the ratio only.',
    state: 'built',
    builtOn: '2026-09-24',
    ingest: 'scripts/atlas/ingest/cost-of-living.mjs',
    store: 'data/atlas/sources/cost-of-living/normalized.json',
    unlocks: ['cost-of-living.country', 'cost-of-living.country-vs-market', 'comparisons.city-vs-city', 'comparisons.country-vs-country', 'tools.calculator', 'tools.matcher', 'tools.cost-comparison', 'tools.cost-calculator', 'rankings.index', 'relocation.country'],
    refused: 'Numbeo, which every competitor in this space uses and whose terms do not permit redistribution.',
  }),
  'cost-of-living-city-verified': s({
    id: 'cost-of-living-city-verified',
    provider: 'none identified',
    dataset: 'city level consumer price index',
    access: 'unknown',
    licence: 'unknown',
    commercialReuse: null,
    storageRights: null,
    freshnessClass: 'prices',
    refreshInterval: 'unknown',
    cost: null,
    coverage: 'NOT_AVAILABLE',
    state: 'not-built',
    unlocks: ['cost-of-living.city', 'cost-of-living.city-vs-market', 'relocation.city', 'comparisons.city-vs-home'],
    why: 'Split out of the country source on 2026-09-24 rather than letting four city families quietly inherit a national figure and present it as a city one. Eurostat is national. A few national offices publish regional indices and none are comparable across borders.',
  }),
  'places-data-verified': s({
    id: 'places-data-verified',
    provider: 'OpenStreetMap via Geofabrik regional extracts',
    dataset: 'planet extract, amenity and shop tags',
    access: 'bulk pbf download per region, never the Overpass API for bulk',
    licence: 'open-sharealike',
    attribution: 'Data from OpenStreetMap contributors, ODbL',
    commercialReuse: true,
    storageRights: true,
    freshnessClass: 'places',
    refreshInterval: 'monthly per region',
    cost: 0,
    rateLimits: 'none on the extracts; Overpass is rate limited and is not the path',
    coverage: 'global, with density varying between cities by an order of magnitude',
    state: 'not-built',
    fields: ['poiId', 'category', 'subcategory', 'lat', 'lon', 'city', 'neighbourhood', 'address', 'openingHours', 'website', 'operator', 'wheelchair'],
    fieldsNotAvailable: ['rating', 'popularity', 'priceBand'],
    unlocks: ['places.city-category', 'places.neighbourhood-category', 'places.poi', 'services.city-practical'],
    shareAlikeNote: 'ODbL share alike applies to a derived database, not to a produced work. Displaying OSM facts on a page is safe. Publishing a combined dataset may not be, and that question has to be answered before any Livdar owned attributes are mixed into the same store. The ingest keeps the OSM base and Livdar attributes in separate stores for exactly this reason.',
    refused: 'Google Places, whose terms forbid storing the fields that would supply ratings and price bands.',
  }),
  'neighbourhood-facts-verified': s({
    id: 'neighbourhood-facts-verified',
    provider: 'OpenStreetMap plus national census and city open data',
    dataset: 'admin boundaries, population grids, amenity counts',
    access: 'bulk per country',
    licence: 'open-sharealike',
    attribution: 'OpenStreetMap contributors, ODbL, plus each national statistical office',
    commercialReuse: true,
    storageRights: true,
    freshnessClass: 'reference',
    refreshInterval: 'annual',
    cost: 0,
    coverage: 'good in Europe and North America, uneven elsewhere',
    state: 'not-built',
    dependsOn: ['places-data-verified'],
    unlocks: ['neighbourhoods.city-best-for', 'neighbourhoods.guide', 'places.neighbourhood-category', 'rents.neighbourhood'],
    note: 'Boundaries are the hard part and they come from OSM. Everything else is a count over the places layer, which is why this is built after it rather than beside it.',
  }),
  'salary-data-verified': s({
    id: 'salary-data-verified',
    provider: 'national statistical offices, Eurostat earn_ses series for the EU',
    dataset: 'structure of earnings survey and national equivalents',
    access: 'bulk, per country',
    licence: 'open',
    attribution: 'per office',
    commercialReuse: true,
    storageRights: true,
    freshnessClass: 'salary',
    refreshInterval: 'annual, several offices every four years',
    cost: 0,
    coverage: 'EU plus the larger OECD members. Occupation detail varies and the classifications differ.',
    state: 'not-built',
    unlocks: ['work.city-salaries', 'work.city-jobs-category', 'tools.calculator'],
    hazard: 'The real risk here is combining incompatible series. Gross against net, monthly against annual, mean against median, and four different occupation classifications. The adapter must record which of each it holds per country and refuse to compare across them.',
  }),
  'rent-index-verified': s({
    id: 'rent-index-verified',
    provider: 'national statistical offices and city housing observatories',
    dataset: 'rent price indices and, where published, levels',
    access: 'bulk, per country',
    licence: 'open',
    attribution: 'per office',
    commercialReuse: true,
    storageRights: true,
    freshnessClass: 'rent',
    refreshInterval: 'quarterly where it exists',
    cost: 0,
    coverage: 'partial by design. Some countries publish city level levels, some publish national indices only, some publish nothing.',
    state: 'not-built',
    unlocks: ['rents.city', 'rents.neighbourhood', 'tools.calculator', 'neighbourhoods.city-best-for'],
    refused: 'Scraping rental marketplaces, which is both against their terms and a biased sample of asking prices rather than rents paid.',
  }),
  'visa-rules-verified': s({
    id: 'visa-rules-verified',
    provider: 'destination government publications',
    dataset: 'entry, residence and remote work permissions',
    access: 'manual reading, no API anywhere',
    licence: 'public-sector',
    attribution: 'per country, citing the official page and the date read',
    commercialReuse: true,
    storageRights: true,
    freshnessClass: 'rules',
    refreshInterval: 'recheck every 30 days, expire at 90',
    cost: 'staff time only',
    coverage: 'whatever is entered, starting with the eleven priority destinations',
    state: 'not-built',
    unlocks: ['visas.country-visit', 'visas.country-residency', 'visas.country-digital-nomad', 'visas.country-work-permit', 'relocation.country', 'relocation.city', 'services.country-admin'],
    hazard: 'This is the source where being wrong causes harm rather than embarrassment. Nothing may be entered from memory or from a secondary source. Every field cites the official page it came from and the date it was read, and the schema refuses a record that does not.',
  }),
  'work-rules-verified': s({
    id: 'work-rules-verified',
    provider: 'destination government publications',
    dataset: 'right to work, sponsorship, employment conditions',
    access: 'manual',
    licence: 'public-sector',
    attribution: 'per country',
    commercialReuse: true,
    storageRights: true,
    freshnessClass: 'rules',
    refreshInterval: 'recheck every 30 days',
    cost: 'staff time only',
    coverage: 'the eleven priority destinations first',
    state: 'not-built',
    dependsOn: ['visa-rules-verified'],
    unlocks: ['work.country-working', 'work.city-jobs-category'],
    note: 'Built alongside visas because the same official pages usually carry both.',
  }),
  'tax-rules-verified': s({
    id: 'tax-rules-verified',
    provider: 'national tax authorities, with the OECD tax database as a cross check',
    dataset: 'residency thresholds, personal income tax, social contributions, treaty network',
    access: 'manual',
    licence: 'public-sector',
    attribution: 'per country',
    commercialReuse: true,
    storageRights: true,
    freshnessClass: 'rules',
    refreshInterval: 'annual at the budget, recheck every 30 days',
    cost: 'staff time only',
    coverage: 'the eleven priority destinations first',
    state: 'not-built',
    unlocks: ['taxes.country', 'taxes.country-remote-work', 'comparisons.country-vs-country', 'tools.calculator'],
    hazard: 'Same as visas. Structured facts with a citation, never advice, and never a computed liability presented as one.',
  }),
  'events-verified': s({
    id: 'events-verified',
    provider: 'none identified',
    dataset: 'event listings with dates and venues',
    access: 'unknown',
    licence: 'display-only',
    licenceNote: 'At best. Most candidate providers forbid redistribution outright and the ones that permit anything permit display beside a link.',
    commercialReuse: false,
    storageRights: false,
    freshnessClass: 'events',
    refreshInterval: 'daily',
    cost: null,
    coverage: 'NOT_AVAILABLE',
    state: 'not-built',
    unlocks: ['events.city-window', 'events.city-type', 'events.recurring', 'events.series-city', 'events.city-calendar'],
    routes: [
      'An affiliate agreement with a ticketing platform, which permits the display the temporal hubs need and pays for the click.',
      'City open data portals, which exist for perhaps a dozen cities, in a different schema each time.',
      'First party venue and community feeds once Livdar has partners.',
    ],
    refused: 'Scraping Ticketmaster, Eventbrite, Meetup or Fever. Their terms forbid it, and a surface built on a scrape is a surface that disappears without notice.',
    note: 'This is the highest volume surface in the programme and the least licensable. It stays blocked. Nothing about that is solved by more keyword research.',
  }),
  'stay-inventory-verified': s({
    id: 'stay-inventory-verified',
    provider: 'a booking affiliate for hotels, a marketplace partner for the rest',
    dataset: 'availability and prices',
    access: 'partner API',
    licence: 'contractual',
    commercialReuse: null,
    storageRights: 'usually no, caching windows are set by the agreement',
    freshnessClass: 'live',
    refreshInterval: 'continuous',
    cost: 'revenue share rather than a fee',
    coverage: 'hotels are global, rooms and coliving are concentrated where those markets exist',
    state: 'not-built',
    unlocks: ['stay.city-type', 'stay.near-venue'],
    note: 'Not a technical problem. The measurement is unusually good, with hotels near a venue at 3,000 a month, difficulty 2 and a dollar forty a click, and what is missing is a contract.',
  }),
  'sport-routes-verified': s({
    id: 'sport-routes-verified',
    provider: 'OpenStreetMap for routes, an open forecast source for conditions',
    dataset: 'route relations and paths, elevation, marine and wind forecasts',
    access: 'bulk for routes, API for conditions',
    licence: 'open-sharealike',
    attribution: 'OpenStreetMap contributors, ODbL, plus the forecast provider',
    commercialReuse: true,
    storageRights: 'yes for routes, usually no for forecasts',
    freshnessClass: 'places',
    refreshInterval: 'monthly for routes, hourly for conditions',
    cost: 0,
    coverage: 'good in Europe and North America, thin elsewhere',
    state: 'not-built',
    dependsOn: ['places-data-verified'],
    unlocks: ['sport.city-activity', 'sport.route'],
    separation: 'Route geometry, difficulty and surface are stored. Conditions and forecasts are fetched and cached, never stored as facts, because they are true for hours.',
    refused: 'Strava route data, whose API terms do not permit republishing routes.',
  }),
  'community-listings-verified': s({
    id: 'community-listings-verified',
    provider: 'Livdar first party data',
    dataset: 'groups and recurring meetups',
    access: 'internal',
    licence: 'open',
    commercialReuse: true,
    storageRights: true,
    freshnessClass: 'events',
    refreshInterval: 'continuous',
    cost: 0,
    coverage: 'starts empty and grows with the product',
    state: 'not-built',
    unlocks: ['community.city-topic'],
    note: 'First party or nothing. Every platform that holds this data forbids redistributing it, which is also why the family indexes the hub and never the group.',
  }),
  'venue-data-verified': s({
    id: 'venue-data-verified',
    provider: 'Wikidata',
    dataset: 'SPARQL over five venue classes: stadium, sports venue, concert hall, event venue, arena',
    access: 'public SPARQL endpoint, fetched through a browser because the sandbox has no network route to it',
    licence: 'open',
    attribution: 'Venue records from Wikidata (CC0)',
    commercialReuse: true,
    storageRights: true,
    freshnessClass: 'reference',
    refreshInterval: 'yearly',
    cost: 0,
    coverage: '9,438 venues across 3,766 cities in 16 countries, 4,145 of them with a capacity. 517 were refused for sitting more than 40km from any city in the entity store and 5 for an impossible capacity.',
    state: 'built',
    ingest: 'scripts/atlas/ingest/venues.mjs',
    store: 'data/atlas/sources/venues/by-country/*.json',
    unlocks: ['stay.near-venue'],
    note: 'Built on 24 September. The cost of it being cheap is confidence: Wikidata is community edited, so every value carries `declared`, the lowest rank that publishes at all. A venue page may say where a venue is and roughly how large it is; it may not present the capacity as the operator\'s own figure, and a family that needs an official number still needs the operator.',
  }),
  'climate-normals-verified': s({
    id: 'climate-normals-verified',
    provider: 'NASA POWER',
    dataset: 'Climatology endpoint, twenty year monthly normals for 2001-2020',
    access: 'public JSON API, fetched through a browser because the sandbox has no network route to it',
    licence: 'open',
    attribution: 'NASA Langley Research Center POWER Project, funded through the NASA Earth Science Directorate Applied Science Program',
    commercialReuse: true,
    storageRights: true,
    freshnessClass: 'reference',
    refreshInterval: 'when the provider publishes a new normals period',
    cost: 0,
    coverage: '55 cities across 23 countries, every one on the single period 2001-2020 so that cities inside a country can be compared with each other.',
    state: 'built',
    ingest: 'scripts/atlas/ingest/climate-normals.mjs',
    store: 'data/atlas/sources/climate/normals.json',
    unlocks: ['weather.country-best-time'],
    note: 'Only the mean temperature is a normal. The provider\'s T2M_MAX and T2M_MIN on this endpoint are the extreme values over the whole period rather than the mean daily maximum and minimum, which is why they are stored as tmaxExtreme and tminExtreme and never scored. No page built on this may state a typical daytime high or overnight low, and the values describe a 0.5 by 0.625 degree model cell rather than a weather station, so the confidence is `official-proxy` and the page says so.',
  }),
  'item-price-verified': s({
    id: 'item-price-verified',
    provider: 'European Commission Weekly Oil Bulletin for fuel, national statistical offices for the rest',
    dataset: 'single item consumer prices',
    access: 'bulk',
    licence: 'open',
    attribution: 'per source',
    commercialReuse: true,
    storageRights: true,
    freshnessClass: 'prices',
    refreshInterval: 'weekly for fuel, monthly for the rest',
    cost: 0,
    coverage: 'fuel is EU wide and weekly, food and transport are per country',
    state: 'not-built',
    unlocks: ['cost-of-living.item-country'],
  }),
};

export const SOURCE_IDS = Object.keys(SOURCES);

export const built = () => SOURCE_IDS.filter((id) => SOURCES[id].state === 'built');
export const blocked = () => SOURCE_IDS.filter((id) => SOURCES[id].state !== 'built');

// What building one source would unlock, so the order of work is a
// calculation rather than an opinion.
export function impact(id, familiesBySource) {
  const src = SOURCES[id];
  if (!src) throw new Error('unknown source: ' + id);
  const fams = familiesBySource[id] || [];
  return {
    id,
    state: src.state,
    families: fams.length,
    candidates: fams.reduce((t, f) => t + (f.candidates || 0), 0),
    licence: src.licence,
    cost: src.cost,
    dependsOn: src.dependsOn || [],
    buildable: src.licence === 'open' || src.licence === 'open-sharealike' || src.licence === 'public-sector',
  };
}

export function validateRegistry() {
  const errors = [];
  for (const [id, src] of Object.entries(SOURCES)) {
    if (src.id !== id) errors.push(id + ' has a mismatched id');
    if (!STATES.includes(src.state)) errors.push(id + ' has state ' + src.state);
    if (!LICENCE_CLASSES[src.licence]) errors.push(id + ' has licence class ' + src.licence);
    if (!Array.isArray(src.unlocks) || !src.unlocks.length) errors.push(id + ' unlocks nothing, so nobody needs it');
    if (src.state === 'built' && !src.ingest) errors.push(id + ' is built with no ingest script recorded');
    if (src.state === 'built' && !src.store) errors.push(id + ' is built with no store recorded');
    if (src.commercialReuse === false && src.state === 'built') errors.push(id + ' is built and does not permit commercial reuse');
    for (const d of src.dependsOn || []) if (!SOURCES[d]) errors.push(id + ' depends on unknown source ' + d);
  }
  return errors;
}
