import { readFileSync } from 'node:fs';
import { taxonomyCapacity } from '../lib/programmatic/eligibility.js';

const taxonomy = JSON.parse(readFileSync(new URL('../data/programmatic-taxonomy.json', import.meta.url), 'utf8'));

console.log('Livdar master taxonomy');
console.log('  version: ' + taxonomy.version);
console.log('  status: ' + taxonomy.status);
console.log('  generation: ' + (taxonomy.generationEnabled ? 'enabled' : 'disabled'));
console.log('  families: ' + taxonomy.families.length);
console.log('  declared dimension combinations: ' + taxonomyCapacity(taxonomy).toLocaleString('en-US'));
console.log('  scale targets: ' + taxonomy.scaleTargets.map((value) => value.toLocaleString('en-US')).join(', '));
console.log('  hard gates: ' + taxonomy.hardGates.length);
console.log('');
console.log('No URLs are generated by this report. Candidates enter routing only after every hard gate passes.');
