// What each ranking means, written for each ranking.
//
// The cheapest list and the most expensive list are the same measure sorted
// two ways, and the first version of these pages was two copies of one page
// with the ends swapped. The near duplicate detector caught it at eighty four
// percent, and again it was right: reversing a sort is not writing a second
// page.
//
// What actually differs is what the reader should take from each end. A low
// price level usually travels with low wages and a weak currency, so cheap is
// not the same as good value for somebody earning locally. A high price level
// usually travels with high wages, so expensive is not the same as
// unaffordable. Those are two different warnings and they are the reason the
// two pages exist separately.

const T = {
  'cheapest-countries': {
    en: 'A low price level rarely arrives on its own. It usually travels with lower wages and a weaker currency, so a country near the top of this list is cheap for somebody arriving with income from elsewhere and not necessarily cheap for somebody earning there. The ranking is most useful read next to the pay figures for the same country, and least useful read as a recommendation.',
    de: 'Ein niedriges Preisniveau kommt selten allein. Es geht meist mit niedrigeren Löhnen und einer schwächeren Währung einher, ein Land weit oben in dieser Liste ist also günstig für jemanden, der sein Einkommen von woanders mitbringt, und nicht zwangsläufig günstig für jemanden, der dort verdient. Am nützlichsten ist die Liste neben den Verdienstzahlen desselben Landes, am wenigsten nützlich als Empfehlung.',
    fr: "Un niveau des prix bas arrive rarement seul. Il va le plus souvent avec des salaires plus faibles et une monnaie plus faible, donc un pays en haut de cette liste est bon marché pour qui arrive avec un revenu venu d'ailleurs, et pas forcément pour qui gagne sa vie sur place. Le classement est utile lu à côté des salaires du même pays, et inutile lu comme une recommandation.",
    es: 'Un nivel de precios bajo casi nunca llega solo. Suele venir con sueldos más bajos y una moneda más débil, así que un país en lo alto de esta lista es barato para quien llega con ingresos de fuera, y no necesariamente para quien cobra allí. La lista se aprovecha leída al lado de los salarios del mismo país, y no sirve de nada leída como una recomendación.',
    it: "Un livello dei prezzi basso arriva di rado da solo. Di solito viaggia insieme a retribuzioni più basse e a una valuta più debole, quindi un paese in cima a questa lista è economico per chi arriva con un reddito da altrove e non per forza per chi lì ci lavora. La classifica serve letta accanto alle retribuzioni dello stesso paese, e non serve a nulla letta come un consiglio.",
    pt: 'Um nível de preços baixo raramente chega sozinho. Costuma vir com ordenados mais baixos e uma moeda mais fraca, por isso um país no topo desta lista é barato para quem chega com rendimento de fora e não necessariamente para quem ganha lá. A lista aproveita-se lida ao lado dos salários do mesmo país, e não serve de nada lida como recomendação.',
    nl: 'Een laag prijspeil komt zelden alleen. Het gaat meestal samen met lagere lonen en een zwakkere munt, dus een land bovenaan deze lijst is goedkoop voor wie met inkomen van elders aankomt en niet per se voor wie daar verdient. De lijst is het nuttigst naast de looncijfers van hetzelfde land, en het minst nuttig als aanbeveling.',
    pl: 'Niski poziom cen rzadko przychodzi sam. Zwykle idzie w parze z niższymi płacami i słabszą walutą, więc kraj na czele tej listy jest tani dla kogoś, kto przyjeżdża z dochodem skądinąd, a niekoniecznie dla kogoś, kto zarabia na miejscu. Ta lista przydaje się czytana obok wynagrodzeń tego samego kraju, a na nic się nie zda czytana jak rekomendacja.',
    ja: '物価の低さは単独では現れにくい。たいていは賃金の低さと通貨の弱さを伴うので、この一覧の上位にある国は、よそからの収入を持って来る人にとって安いのであって、そこで稼ぐ人にとって必ずしも安いわけではない。同じ国の賃金の数字と並べて読むときに最も役に立ち、おすすめの一覧として読むときには何の役にも立たない。',
  },
  'most-expensive-countries': {
    en: 'Expensive is not the same as unaffordable. The countries at the top of this list are mostly high wage economies with strong currencies, and a resident earning locally may be no worse off than somebody in a cheap country earning local wages there. The list answers what a visitor or a newcomer pays, which is the case where a high price level genuinely hurts, because the income has not moved with the prices.',
    de: 'Teuer ist nicht dasselbe wie unbezahlbar. Oben in dieser Liste stehen überwiegend Hochlohnländer mit starken Währungen, und wer dort vor Ort verdient, steht womöglich nicht schlechter da als jemand in einem günstigen Land mit dortigem Lohn. Die Liste beantwortet, was ein Besucher oder ein Zugezogener zahlt, und genau dort tut ein hohes Preisniveau wirklich weh, weil das Einkommen den Preisen nicht gefolgt ist.',
    fr: "Cher n'est pas la même chose qu'inabordable. En haut de cette liste on trouve surtout des économies à hauts salaires et à monnaie forte, et un résident qui gagne sa vie sur place n'est pas forcément moins bien loti que quelqu'un qui gagne un salaire local dans un pays bon marché. Le classement répond à ce que paie un visiteur ou un nouvel arrivant, et c'est là qu'un niveau des prix élevé fait vraiment mal, parce que le revenu n'a pas suivi les prix.",
    es: 'Caro no es lo mismo que inasequible. Arriba de esta lista hay sobre todo economías de salarios altos con monedas fuertes, y quien vive y cobra allí puede no estar peor que quien cobra sueldo local en un país barato. La lista responde a lo que paga un visitante o un recién llegado, que es donde un nivel de precios alto duele de verdad, porque el ingreso no se ha movido con los precios.',
    it: "Caro non è la stessa cosa di inaccessibile. In cima a questa lista ci sono soprattutto economie ad alti salari con valute forti, e chi vive e guadagna lì può non stare peggio di chi prende uno stipendio locale in un paese economico. La classifica risponde a quanto paga chi visita o chi è appena arrivato, ed è lì che un livello dei prezzi alto fa davvero male, perché il reddito non si è mosso insieme ai prezzi.",
    pt: 'Caro não é o mesmo que incomportável. No topo desta lista estão sobretudo economias de salários altos com moedas fortes, e quem vive e ganha lá pode não estar pior do que quem recebe ordenado local num país barato. A lista responde ao que paga quem visita ou quem acabou de chegar, e é aí que um nível de preços alto dói mesmo, porque o rendimento não acompanhou os preços.',
    nl: 'Duur is niet hetzelfde als onbetaalbaar. Bovenaan deze lijst staan vooral economieën met hoge lonen en sterke munten, en wie daar woont en verdient is misschien niet slechter af dan wie in een goedkoop land een lokaal loon krijgt. De lijst beantwoordt wat een bezoeker of een nieuwkomer betaalt, en daar doet een hoog prijspeil werkelijk pijn, omdat het inkomen niet met de prijzen is meegegaan.',
    pl: 'Drogo to nie to samo co nie do udźwignięcia. Na czele tej listy stoją głównie gospodarki o wysokich płacach i mocnych walutach, a ktoś, kto tam mieszka i zarabia, wcale nie musi być w gorszej sytuacji niż ktoś, kto pobiera miejscową pensję w tanim kraju. Lista odpowiada na to, ile płaci odwiedzający albo świeżo przybyły, i właśnie tam wysoki poziom cen boli naprawdę, bo dochód nie poszedł za cenami.',
    ja: '高いことと、手が届かないことは同じではない。この一覧の上位に並ぶのはおおむね賃金の高い、通貨の強い国であり、そこで働いて稼いでいる住人は、安い国で現地の賃金をもらっている人より苦しいとは限らない。この一覧が答えるのは、訪れる人や来たばかりの人が払う額である。物価の高さが本当にこたえるのはそこで、収入のほうが物価についてきていないからだ。',
  },
  'cheapest-countries-europe': {
    en: 'Europe is the one place where this comparison is on firm ground. Almost every country here is measured by the same institution on the same definition in the same year, which is rarely true of a world list, so the gaps between neighbours mean what they appear to mean. It also makes the spread visible: the distance between the cheapest and the dearest country inside a single continent and largely a single market is wider than most people expect.',
    de: 'Europa ist der eine Ort, an dem dieser Vergleich festen Boden hat. Fast jedes Land hier wird von derselben Institution nach derselben Definition im selben Jahr gemessen, was bei einer Weltliste selten zutrifft, die Abstände zwischen Nachbarn bedeuten also, was sie zu bedeuten scheinen. Das macht auch die Spanne sichtbar: der Abstand zwischen dem günstigsten und dem teuersten Land innerhalb eines Kontinents und weitgehend eines Binnenmarktes ist größer, als die meisten erwarten.',
    fr: "L'Europe est le seul endroit où cette comparaison repose sur du solide. Presque tous les pays y sont mesurés par la même institution, selon la même définition et la même année, ce qui est rarement vrai d'une liste mondiale : les écarts entre voisins veulent donc bien dire ce qu'ils ont l'air de dire. Cela rend aussi l'amplitude visible : la distance entre le pays le moins cher et le plus cher, à l'intérieur d'un continent et pour l'essentiel d'un même marché, est plus large qu'on ne l'imagine.",
    es: 'Europa es el único sitio donde esta comparación pisa terreno firme. Casi todos los países de aquí los mide la misma institución con la misma definición y el mismo año, cosa que rara vez pasa en una lista mundial, así que las distancias entre vecinos significan lo que parecen significar. Eso también deja ver la amplitud: la distancia entre el país más barato y el más caro dentro de un continente y en buena medida de un solo mercado es mayor de lo que casi nadie espera.',
    it: "L'Europa è l'unico posto in cui questo confronto poggia su terreno solido. Quasi tutti i paesi qui sono misurati dalla stessa istituzione con la stessa definizione nello stesso anno, cosa che raramente vale per una lista mondiale, quindi le distanze fra vicini significano quello che sembrano significare. Questo rende visibile anche l'ampiezza: la distanza fra il paese più economico e il più caro dentro un continente e in gran parte un mercato solo è più larga di quanto quasi nessuno si aspetti.",
    pt: 'A Europa é o único sítio onde esta comparação assenta em terreno firme. Quase todos os países aqui são medidos pela mesma instituição, com a mesma definição e no mesmo ano, o que raramente acontece numa lista mundial, por isso as distâncias entre vizinhos querem dizer o que parecem querer dizer. Isso deixa também ver a amplitude: a distância entre o país mais barato e o mais caro dentro de um continente e em boa parte de um só mercado é maior do que quase toda a gente espera.',
    nl: 'Europa is de ene plek waar deze vergelijking op vaste grond staat. Bijna elk land hier wordt door dezelfde instelling volgens dezelfde definitie in hetzelfde jaar gemeten, wat bij een wereldlijst zelden opgaat, dus de afstanden tussen buren betekenen wat ze lijken te betekenen. Het maakt ook de spreiding zichtbaar: de afstand tussen het goedkoopste en het duurste land binnen één werelddeel en grotendeels één markt is groter dan de meesten verwachten.',
    pl: 'Europa to jedyne miejsce, gdzie takie porównanie stoi na twardym gruncie. Niemal każdy kraj jest tu mierzony przez tę samą instytucję, tą samą definicją i w tym samym roku, co przy liście światowej zdarza się rzadko, więc odległości między sąsiadami znaczą to, na co wyglądają. Widać dzięki temu także rozpiętość: odległość między najtańszym a najdroższym krajem wewnątrz jednego kontynentu i w dużej mierze jednego rynku jest większa, niż większość ludzi się spodziewa.',
    ja: 'この比較が確かな足場に立てる唯一の場所がヨーロッパである。ここに並ぶ国のほとんどは、同じ機関が同じ定義で同じ年に測っている。世界規模の一覧ではまず成り立たない条件で、だから隣国どうしの差は見た目どおりの意味を持つ。開きも見えてくる。一つの大陸、しかも大部分は一つの市場のなかで、最も安い国と最も高い国の距離は、たいていの人が思うより広い。',
  },
};

export const rankingCopy = (id, language) => (T[id] ? T[id][language] || null : null);
export function missingRankingCopy(ids, languages) {
  const gaps = [];
  for (const id of ids) for (const l of languages) if (!rankingCopy(id, l)) gaps.push(id + ' has no copy in ' + l);
  return gaps;
}
