// What each tool actually does, in each language.
//
// This file exists because the generic tool page failed its own quality
// check. Eight calculators sharing one description of how calculators work
// came out of the near duplicate detector at ninety eight percent similar,
// and the detector was right: a page that says nothing about the particular
// tool it is about should not be published, however true the general sentences
// on it are.
//
// So every tool says, in its own words and in every language, what question
// it answers and which question it refuses. The refusal is the more useful
// half. A travel budget tool that says out loud that it cannot price a
// specific hotel is more trustworthy than one that quietly produces a number
// anyway, and it is the sentence that distinguishes this page from the seven
// others.

const T = {
  'salary-calculator': {
    en: 'The question here is what a job pays in one country against another, measured on the same definition in both. The published series covers a single person on the average wage, before and after tax, which is the only comparison that holds across borders: a headline salary in one country is taxed differently in the next, and two gross figures from two tax systems are not the same number twice. What it cannot do is price a particular job. Occupation, sector, seniority and employer all move pay more than the country does, and none of them is in this series.',
    de: 'Die Frage ist, was eine Arbeit in einem Land im Vergleich zu einem anderen einbringt, gemessen nach derselben Definition. Die veröffentlichte Reihe erfasst eine alleinstehende Person mit Durchschnittsverdienst, vor und nach Abzügen, und nur dieser Vergleich hält über Grenzen hinweg: ein Bruttogehalt wird im Nachbarland anders besteuert, zwei Bruttozahlen aus zwei Steuersystemen sind nicht zweimal dieselbe Zahl. Was der Rechner nicht kann, ist eine bestimmte Stelle zu bewerten. Beruf, Branche, Erfahrung und Arbeitgeber bewegen das Gehalt stärker als das Land, und nichts davon steckt in dieser Reihe.',
    fr: "La question est de savoir ce que rapporte un travail dans un pays par rapport à un autre, mesuré selon la même définition des deux côtés. La série publiée couvre une personne seule au salaire moyen, avant et après prélèvements, et c'est la seule comparaison qui tienne d'un pays à l'autre : un salaire brut n'est pas imposé de la même façon chez le voisin, et deux montants bruts venus de deux systèmes fiscaux ne sont pas deux fois le même chiffre. Ce que l'outil ne peut pas faire, c'est évaluer un poste précis. Le métier, le secteur, l'ancienneté et l'employeur pèsent plus que le pays, et rien de tout cela n'est dans cette série.",
    es: 'La pregunta es qué paga un trabajo en un país frente a otro, medido con la misma definición en ambos. La serie publicada cubre a una persona sola con salario medio, antes y después de impuestos, y esa es la única comparación que aguanta de una frontera a otra: un bruto no tributa igual en el país vecino, y dos cifras brutas de dos sistemas fiscales no son dos veces la misma cifra. Lo que no puede hacer es poner precio a un puesto concreto. Oficio, sector, antigüedad y empresa mueven el sueldo más que el país, y nada de eso está en esta serie.',
    it: "La domanda è quanto rende un lavoro in un paese rispetto a un altro, misurato con la stessa definizione da entrambe le parti. La serie pubblicata copre una persona sola con retribuzione media, prima e dopo il prelievo, ed è l'unico confronto che regge fra un paese e l'altro: un lordo non viene tassato allo stesso modo oltre confine, e due importi lordi di due sistemi fiscali non sono due volte lo stesso numero. Quello che lo strumento non può fare è valutare un posto preciso. Mestiere, settore, anzianità e datore di lavoro spostano la retribuzione più del paese, e niente di tutto questo sta in questa serie.",
    pt: 'A pergunta é quanto rende um trabalho num país face a outro, medido pela mesma definição dos dois lados. A série publicada cobre uma pessoa sozinha com salário médio, antes e depois de impostos, e é a única comparação que aguenta de fronteira para fronteira: um bruto não é tributado da mesma maneira no país ao lado, e dois valores brutos de dois sistemas fiscais não são duas vezes o mesmo número. O que não consegue fazer é pôr preço a um posto concreto. Profissão, setor, antiguidade e empregador mexem no ordenado mais do que o país, e nada disso está nesta série.',
    nl: 'De vraag is wat werk in het ene land oplevert tegenover het andere, gemeten volgens dezelfde definitie aan beide kanten. De gepubliceerde reeks dekt een alleenstaande met een gemiddeld loon, voor en na inhoudingen, en dat is de enige vergelijking die over de grens standhoudt: een brutoloon wordt in het buurland anders belast, en twee brutobedragen uit twee belastingstelsels zijn niet twee keer hetzelfde getal. Wat het niet kan, is een bepaalde baan waarderen. Beroep, sector, ervaring en werkgever bewegen het loon meer dan het land, en daar zit niets van in deze reeks.',
    pl: 'Pytanie brzmi, ile daje praca w jednym kraju wobec drugiego, mierzone tą samą definicją po obu stronach. Opublikowana seria obejmuje osobę samotną o przeciętnym wynagrodzeniu, przed potrąceniami i po nich, i tylko takie porównanie wytrzymuje przekroczenie granicy: kwota brutto jest u sąsiada opodatkowana inaczej, a dwie kwoty brutto z dwóch systemów podatkowych to nie dwa razy ta sama liczba. Czego narzędzie nie potrafi, to wycenić konkretnego stanowiska. Zawód, branża, staż i pracodawca ruszają płacę mocniej niż kraj, a nic z tego nie siedzi w tej serii.',
    ja: '問いは、ある国の仕事が別の国と比べていくらになるかであり、両方を同じ定義で測っている。公表されている系列が扱うのは平均賃金の単身者で、控除の前と後の両方。国境をまたいでも成り立つ比較はこれだけである。総支給は隣の国では別の課税を受けるので、二つの税制から出た二つの総支給額は同じ数字が二度あるわけではない。この計算ができないのは、特定の求人を値付けすることである。職種、業種、経験、雇い主のほうが国よりも給与を動かすが、そのどれもこの系列には入っていない。',
  },
  'cost-of-living-comparison': {
    en: 'The question here is which of two places is dearer, and by how much. It is answered by putting the same standard basket in both and reading the gap, which is why the pair has to be measured on one scale: comparing a country on the European index with a country on the World Bank ratio produces a number, and the number means nothing. The comparison refuses that pairing instead of converting between the two, because the conversion would be an invention. It also cannot tell you whether you would be better off, which depends on your income and not on the basket.',
    de: 'Die Frage ist, welcher von zwei Orten teurer ist und um wie viel. Beantwortet wird sie, indem derselbe genormte Warenkorb in beide gelegt und der Abstand abgelesen wird, und deshalb muss das Paar auf einer Skala gemessen sein: ein Land auf dem europäischen Index mit einem Land auf dem Weltbank-Verhältnis zu vergleichen ergibt eine Zahl, und die Zahl bedeutet nichts. Der Vergleich verweigert dieses Paar, statt zwischen beiden umzurechnen, denn die Umrechnung wäre erfunden. Ob es Ihnen besser ginge, sagt er auch nicht, das hängt an Ihrem Einkommen und nicht am Warenkorb.',
    fr: "La question est de savoir lequel de deux endroits est le plus cher, et de combien. On y répond en plaçant le même panier normalisé dans les deux et en lisant l'écart, et c'est pourquoi la paire doit être mesurée sur une seule échelle : comparer un pays de l'indice européen à un pays du rapport de la Banque mondiale donne un nombre, et ce nombre ne veut rien dire. La comparaison refuse cet appariement au lieu de convertir entre les deux, car la conversion serait inventée. Elle ne dit pas non plus si vous y seriez mieux : cela dépend de votre revenu et pas du panier.",
    es: 'La pregunta es cuál de dos sitios es más caro, y por cuánto. Se responde poniendo la misma cesta normalizada en ambos y leyendo la distancia, y por eso la pareja tiene que estar medida en una sola escala: comparar un país del índice europeo con uno de la proporción del Banco Mundial da un número, y ese número no significa nada. La comparación rechaza esa pareja en lugar de convertir entre las dos escalas, porque la conversión sería inventada. Tampoco te dice si estarías mejor: eso depende de tus ingresos y no de la cesta.',
    it: "La domanda è quale di due posti sia più caro, e di quanto. Si risponde mettendo lo stesso paniere standard in entrambi e leggendo la distanza, ed è per questo che la coppia deve stare su una sola scala: confrontare un paese dell'indice europeo con uno del rapporto della Banca mondiale produce un numero, e quel numero non significa nulla. Il confronto rifiuta quella coppia invece di convertire fra le due scale, perché la conversione sarebbe inventata. Non dice nemmeno se ci staresti meglio: questo dipende dal tuo reddito e non dal paniere.",
    pt: 'A pergunta é qual de dois sítios é mais caro, e por quanto. Responde-se pondo o mesmo cabaz padronizado nos dois e lendo a distância, e é por isso que o par tem de estar medido numa só escala: comparar um país do índice europeu com um da razão do Banco Mundial dá um número, e esse número não quer dizer nada. A comparação recusa esse par em vez de converter entre as duas escalas, porque a conversão seria inventada. Também não diz se estaria melhor: isso depende do seu rendimento e não do cabaz.',
    nl: 'De vraag is welke van twee plaatsen duurder is, en hoeveel. Het antwoord komt door hetzelfde gestandaardiseerde mandje in beide te leggen en het verschil af te lezen, en daarom moet het paar op één schaal gemeten zijn: een land van de Europese index vergelijken met een land van de Wereldbankverhouding levert een getal op, en dat getal betekent niets. De vergelijking weigert dat paar in plaats van tussen de twee schalen om te rekenen, want die omrekening zou verzonnen zijn. Of u er beter van wordt zegt hij ook niet: dat hangt van uw inkomen af en niet van het mandje.',
    pl: 'Pytanie brzmi, które z dwóch miejsc jest droższe i o ile. Odpowiedź powstaje przez włożenie tego samego ustandaryzowanego koszyka w oba i odczytanie różnicy, i właśnie dlatego para musi być mierzona w jednej skali: porównanie kraju z indeksu europejskiego z krajem ze wskaźnika Banku Światowego daje liczbę, a ta liczba nic nie znaczy. Porównanie odrzuca taką parę, zamiast przeliczać między skalami, bo przeliczenie byłoby wymyślone. Nie powie też, czy będzie ci się tam żyło lepiej, bo to zależy od twojego dochodu, a nie od koszyka.',
    ja: '問いは、二つの場所のどちらが高く、どれだけ高いかである。答えは同じ標準的な買い物かごを両方に置いて差を読むことで出る。だから二つは同じ尺度で測られていなければならない。欧州指数の国と世界銀行比率の国を比べれば数字は出るが、その数字には意味がない。この比較は二つの尺度を換算するのではなく、その組み合わせ自体を断る。換算は作り物になるからである。そちらのほうが暮らしが良くなるかどうかも言わない。それは買い物かごではなく収入の問題である。',
  },
  'cost-of-living-calculator': {
    en: 'The question here is what one place costs for one household, rather than how two places compare. That makes it the harder of the two calculators to answer honestly, because a household is not a standard basket: the published index weights spending the way the average household spends it, and almost nobody is the average household. The calculator therefore shows the twelve categories separately and lets the reader weight them, instead of producing a single monthly figure that would be precise and wrong for everyone who reads it.',
    de: 'Die Frage ist, was ein Ort für einen Haushalt kostet, nicht wie zwei Orte zueinander stehen. Das macht ihn zum schwierigeren der beiden Rechner, denn ein Haushalt ist kein genormter Warenkorb: der veröffentlichte Index gewichtet die Ausgaben so, wie der Durchschnittshaushalt sie tätigt, und fast niemand ist der Durchschnittshaushalt. Deshalb zeigt der Rechner die zwölf Gruppen einzeln und überlässt die Gewichtung dem Leser, statt eine einzige Monatszahl auszugeben, die präzise und für jeden Leser falsch wäre.',
    fr: "La question est de savoir ce qu'un endroit coûte à un foyer, et non comment deux endroits se comparent. C'est le plus difficile des deux calculateurs à honorer, car un foyer n'est pas un panier normalisé : l'indice publié pondère les dépenses comme les fait le foyer moyen, et presque personne n'est le foyer moyen. Le calculateur affiche donc les douze postes séparément et laisse le lecteur les pondérer, au lieu de sortir un seul montant mensuel qui serait précis et faux pour chacun de ceux qui le lisent.",
    es: 'La pregunta es qué cuesta un sitio para un hogar, no cómo se comparan dos sitios. Eso lo convierte en el más difícil de los dos calculadores de responder con honestidad, porque un hogar no es una cesta normalizada: el índice publicado pondera el gasto como lo hace el hogar medio, y casi nadie es el hogar medio. Por eso el calculador muestra las doce categorías por separado y deja que el lector las pondere, en lugar de sacar una única cifra mensual que sería precisa y falsa para todos los que la lean.',
    it: "La domanda è quanto costa un posto per una famiglia, non come stanno due posti a confronto. È il più difficile dei due calcolatori da onorare, perché una famiglia non è un paniere standard: l'indice pubblicato pesa la spesa come la fa la famiglia media, e quasi nessuno è la famiglia media. Il calcolatore mostra quindi le dodici categorie separate e lascia che sia chi legge a pesarle, invece di tirare fuori una sola cifra mensile che sarebbe precisa e sbagliata per chiunque la legga.",
    pt: 'A pergunta é quanto custa um sítio para uma casa, não como se comparam dois sítios. É o mais difícil dos dois calculadores de responder com honestidade, porque uma casa não é um cabaz padronizado: o índice publicado pondera a despesa como a faz a casa média, e quase ninguém é a casa média. Por isso o calculador mostra as doze categorias em separado e deixa quem lê ponderá-las, em vez de dar um único valor mensal que seria preciso e errado para toda a gente que o lesse.',
    nl: 'De vraag is wat één plaats kost voor één huishouden, niet hoe twee plaatsen zich verhouden. Dat maakt hem de moeilijkste van de twee om eerlijk te beantwoorden, want een huishouden is geen gestandaardiseerd mandje: de gepubliceerde index weegt de uitgaven zoals het gemiddelde huishouden ze doet, en vrijwel niemand is het gemiddelde huishouden. De rekenmachine toont daarom de twaalf categorieën apart en laat de lezer ze wegen, in plaats van één maandbedrag te geven dat precies zou zijn en fout voor iedereen die het leest.',
    pl: 'Pytanie brzmi, ile jedno miejsce kosztuje jedno gospodarstwo domowe, a nie jak dwa miejsca wypadają wobec siebie. To trudniejszy z dwóch kalkulatorów, jeśli odpowiadać uczciwie, bo gospodarstwo domowe nie jest ustandaryzowanym koszykiem: opublikowany indeks waży wydatki tak, jak robi to przeciętne gospodarstwo, a prawie nikt nie jest przeciętnym gospodarstwem. Dlatego kalkulator pokazuje dwanaście kategorii osobno i zostawia wagi czytelnikowi, zamiast podawać jedną kwotę miesięczną, która byłaby dokładna i błędna dla każdego, kto ją przeczyta.',
    ja: '問いは、二つの場所を比べることではなく、一つの場所が一つの世帯にいくらかかるかである。正直に答えるなら二つの計算のうち難しいほうになる。世帯は標準的な買い物かごではないからだ。公表された指数は平均的な世帯の使い方で支出に重みをつけているが、平均的な世帯である人はほとんどいない。だからこの計算は十二の品目を別々に示し、重みづけは読む人にゆだねる。月いくらという一つの数字は、精密で、しかも読む人全員にとって間違っているからである。',
  },
  'moving-cost': {
    en: 'The question here is what it costs to move a household from one place to another, and it is the one tool on this site with no statistical office behind it, because no statistical office publishes removal prices. The model is Livdar\'s own: volume, distance, crew hours, packing, insurance and the handling that crossing a border adds. Volume beyond one vehicle becomes a second trip, which is the step a linear estimate misses and the reason cheap online quotes come in low. The answer is always a range with its assumptions attached, never a single number, and it is never a quote.',
    de: 'Die Frage ist, was es kostet, einen Haushalt von einem Ort an einen anderen zu bringen, und das ist das einzige Werkzeug hier ohne ein statistisches Amt dahinter, weil kein statistisches Amt Umzugspreise veröffentlicht. Das Modell ist Livdars eigenes: Volumen, Entfernung, Arbeitsstunden, Verpackung, Versicherung und der Mehraufwand beim Grenzübertritt. Volumen über ein Fahrzeug hinaus wird zur zweiten Fahrt, und genau diesen Sprung übersieht eine lineare Schätzung, weshalb billige Onlineangebote zu niedrig ansetzen. Die Antwort ist immer eine Spanne mit ihren Annahmen, nie eine einzelne Zahl und nie ein Angebot.',
    fr: "La question est de savoir ce que coûte le déménagement d'un foyer, et c'est le seul outil ici sans institut statistique derrière lui, parce qu'aucun institut ne publie de prix de déménagement. Le modèle est celui de Livdar : volume, distance, heures d'équipe, emballage, assurance et la manutention qu'ajoute un passage de frontière. Le volume au delà d'un véhicule devient un second voyage, et c'est la marche qu'une estimation linéaire rate, ce qui explique les devis en ligne trop bas. La réponse est toujours une fourchette avec ses hypothèses, jamais un nombre unique, et jamais un devis.",
    es: 'La pregunta es cuánto cuesta trasladar una casa de un sitio a otro, y es la única herramienta de aquí sin un instituto de estadística detrás, porque ningún instituto publica precios de mudanza. El modelo es propio de Livdar: volumen, distancia, horas de cuadrilla, embalaje, seguro y la manipulación que añade cruzar una frontera. El volumen que no cabe en un vehículo se convierte en un segundo viaje, que es el escalón que una estimación lineal se salta y la razón por la que los presupuestos baratos salen cortos. La respuesta es siempre una horquilla con sus supuestos, nunca un número único, y nunca un presupuesto.',
    it: "La domanda è quanto costa spostare una casa da un posto a un altro, ed è l'unico strumento qui senza un istituto di statistica dietro, perché nessun istituto pubblica i prezzi dei traslochi. Il modello è di Livdar: volume, distanza, ore di squadra, imballaggio, assicurazione e la movimentazione che aggiunge un confine. Il volume che non sta in un veicolo diventa un secondo viaggio, ed è il gradino che una stima lineare salta e il motivo per cui i preventivi online costano troppo poco. La risposta è sempre un intervallo con le sue ipotesi, mai un numero secco, e mai un preventivo.",
    pt: 'A pergunta é quanto custa mudar uma casa de um sítio para outro, e é a única ferramenta aqui sem um instituto de estatística por trás, porque nenhum instituto publica preços de mudanças. O modelo é o da Livdar: volume, distância, horas de equipa, embalagem, seguro e o manuseamento que atravessar uma fronteira acrescenta. O volume que não cabe num veículo passa a ser uma segunda viagem, que é o degrau que uma estimativa linear salta e a razão de os orçamentos baratos saírem curtos. A resposta é sempre um intervalo com os seus pressupostos, nunca um número único, e nunca um orçamento.',
    nl: 'De vraag is wat het kost om een huishouden van de ene plaats naar de andere te brengen, en dit is het enige hulpmiddel hier zonder statistisch bureau erachter, omdat geen enkel bureau verhuisprijzen publiceert. Het model is dat van Livdar zelf: volume, afstand, ploeguren, inpakken, verzekering en de afhandeling die een grens erbij zet. Volume dat niet in één wagen past wordt een tweede rit, en dat is de trede die een lineaire schatting mist en de reden dat goedkope offertes te laag uitvallen. Het antwoord is altijd een bandbreedte met haar aannames, nooit één getal, en nooit een offerte.',
    pl: 'Pytanie brzmi, ile kosztuje przeniesienie gospodarstwa domowego z miejsca na miejsce, i jest to jedyne narzędzie tutaj bez urzędu statystycznego za plecami, bo żaden urząd nie publikuje cen przeprowadzek. Model jest własny, Livdara: objętość, odległość, godziny ekipy, pakowanie, ubezpieczenie i obsługa, którą dokłada przekroczenie granicy. Objętość, która nie mieści się w jednym pojeździe, staje się drugim kursem, a to właśnie ten próg pomija szacunek liniowy i dlatego tanie wyceny w sieci wychodzą za nisko. Odpowiedzią jest zawsze przedział z założeniami, nigdy jedna liczba i nigdy wycena.',
    ja: '問いは、ある場所から別の場所へ家財を運ぶのにいくらかかるかである。ここで統計機関の裏づけがない唯一の道具でもある。引越しの価格を公表している統計機関はないからだ。モデルは Livdar 自身のもので、容積、距離、作業人時、梱包、保険、そして国境を越えるときに加わる荷役から組み立てている。車一台に収まらない容積は二回目の輸送になる。線形の見積もりが落とすのはこの段差で、安いオンライン見積もりが低く出る理由でもある。答えは必ず前提つきの幅であって、一つの数字ではなく、見積書でもない。',
  },
  'where-should-i-live': {
    en: 'The question here is the vaguest one anybody asks and the hardest to answer without flattering the reader. Most quizzes of this shape have no data behind the answer at all: they ask five questions about your personality and name a city. This one filters on measured things, price level and pay and the presence of a source at all, and it returns fewer places than a quiz would because it will not name a country it has no figures for. It cannot weigh what actually decides these moves, which is usually a person or a job rather than a number.',
    de: 'Die Frage ist die vageste, die überhaupt gestellt wird, und die schwerste, ohne dem Leser zu schmeicheln. Die meisten Quizfragen dieser Art haben gar keine Daten hinter der Antwort: fünf Fragen zur Persönlichkeit, dann ein Städtename. Dieses filtert auf Gemessenes, Preisniveau, Verdienst und überhaupt das Vorhandensein einer Quelle, und es nennt weniger Orte als ein Quiz, weil es kein Land nennt, für das es keine Zahlen hat. Was tatsächlich über solche Umzüge entscheidet, kann es nicht gewichten, denn das ist meist ein Mensch oder eine Stelle und keine Zahl.',
    fr: "La question est la plus vague que l'on pose et la plus difficile à traiter sans flatter le lecteur. La plupart des questionnaires de ce genre n'ont aucune donnée derrière la réponse : cinq questions de personnalité et un nom de ville. Celui-ci filtre sur du mesuré, le niveau des prix, la rémunération et l'existence même d'une source, et il renvoie moins d'endroits qu'un questionnaire parce qu'il ne nommera pas un pays dont il n'a pas les chiffres. Il ne sait pas peser ce qui décide vraiment ces départs, qui est le plus souvent une personne ou un emploi et non un nombre.",
    es: 'La pregunta es la más vaga que se hace y la más difícil de tratar sin halagar a quien la hace. Casi todos los test de este tipo no tienen dato alguno detrás de la respuesta: cinco preguntas de personalidad y un nombre de ciudad. Este filtra sobre cosas medidas, nivel de precios, sueldo y la existencia misma de una fuente, y devuelve menos sitios que un test porque no nombrará un país del que no tiene cifras. No sabe pesar lo que de verdad decide estas mudanzas, que suele ser una persona o un trabajo y no un número.',
    it: "La domanda è la più vaga che si faccia e la più difficile da trattare senza lusingare chi legge. Quasi tutti i quiz di questa forma non hanno alcun dato dietro la risposta: cinque domande sul carattere e il nome di una città. Questo filtra su cose misurate, livello dei prezzi, retribuzione e la presenza stessa di una fonte, e restituisce meno posti di un quiz perché non nomina un paese di cui non ha i numeri. Non sa pesare ciò che decide davvero questi spostamenti, che di solito è una persona o un lavoro e non una cifra.",
    pt: 'A pergunta é a mais vaga que se faz e a mais difícil de tratar sem lisonjear quem lê. Quase todos os testes desta forma não têm dado nenhum por trás da resposta: cinco perguntas de personalidade e o nome de uma cidade. Este filtra sobre coisas medidas, nível de preços, ordenado e a própria existência de uma fonte, e devolve menos sítios do que um teste porque não nomeia um país de que não tem números. Não sabe pesar o que decide mesmo estas mudanças, que costuma ser uma pessoa ou um emprego e não um número.',
    nl: 'De vraag is de vaagste die mensen stellen en de moeilijkste om te beantwoorden zonder de lezer te vleien. De meeste testjes van deze vorm hebben helemaal geen data achter het antwoord: vijf vragen over uw karakter en dan een stadsnaam. Deze filtert op gemeten zaken, prijspeil, loon en het bestaan van een bron, en geeft minder plaatsen terug dan een testje omdat hij geen land noemt waarvan hij geen cijfers heeft. Wat zulke verhuizingen werkelijk beslist kan hij niet wegen, want dat is meestal een mens of een baan en geen getal.',
    pl: 'To pytanie jest najbardziej mgliste ze wszystkich i najtrudniejsze do potraktowania bez schlebiania pytającemu. Większość testów tego kształtu nie ma pod odpowiedzią żadnych danych: pięć pytań o charakter i nazwa miasta. Ten filtruje po rzeczach zmierzonych, poziomie cen, wynagrodzeniu i samym istnieniu źródła, i zwraca mniej miejsc niż test, bo nie wymieni kraju, dla którego nie ma liczb. Nie umie zważyć tego, co naprawdę rozstrzyga takie przeprowadzki, a jest to zwykle człowiek albo praca, nie liczba.',
    ja: 'これは人が口にするなかで最も漠然とした問いで、読む人におもねらずに答えるのが最も難しい問いでもある。この形の診断はたいてい答えの裏に何のデータもない。性格を五つ尋ねて都市の名前を返すだけである。ここでは測定された事柄、物価水準、賃金、そもそも出典があるかどうかで絞り込む。だから診断より返る場所は少ない。数字を持たない国の名前は出さないからだ。こうした移住を実際に決めるものは重みづけできない。それはたいてい数字ではなく、人か仕事だからである。',
  },
  'travel-budget': {
    en: 'The question here is what a trip costs per day, which is a different question from what a country costs to live in and is answered with the same source read differently. A resident\'s basket is weighted towards rent and utilities; a visitor\'s is weighted towards restaurants, hotels and transport, and those three categories are published separately, so the estimate uses them rather than the headline. It cannot price a particular hotel or a particular flight, and a tool that claimed to would be reading a price level as though it were a booking engine.',
    de: 'Die Frage ist, was eine Reise pro Tag kostet, und das ist eine andere Frage als die nach den Lebenshaltungskosten eines Landes, beantwortet aus derselben Quelle, nur anders gelesen. Der Warenkorb eines Einwohners liegt schwer auf Miete und Energie, der eines Besuchers auf Restaurants, Hotels und Verkehr, und genau diese drei Gruppen werden einzeln veröffentlicht, also rechnet die Schätzung mit ihnen statt mit der Gesamtzahl. Ein bestimmtes Hotel oder einen bestimmten Flug kann sie nicht bepreisen, und ein Werkzeug, das es behauptete, läse ein Preisniveau wie ein Buchungssystem.',
    fr: "La question est de savoir ce que coûte un voyage par jour, ce qui n'est pas la question du coût de la vie dans un pays et se traite avec la même source lue autrement. Le panier d'un résident pèse sur le loyer et l'énergie, celui d'un visiteur sur les restaurants, les hôtels et les transports, et ces trois postes sont publiés séparément, donc l'estimation s'appuie sur eux plutôt que sur le chiffre d'ensemble. Elle ne peut pas chiffrer un hôtel précis ni un vol précis, et un outil qui le prétendrait lirait un niveau des prix comme s'il était un moteur de réservation.",
    es: 'La pregunta es cuánto cuesta un viaje al día, que no es la pregunta de cuánto cuesta vivir en un país y se responde con la misma fuente leída de otra manera. La cesta de un residente pesa hacia el alquiler y la energía, la de un visitante hacia restaurantes, hoteles y transporte, y esas tres categorías se publican por separado, así que la estimación tira de ellas y no de la cifra general. No puede poner precio a un hotel concreto ni a un vuelo concreto, y una herramienta que dijera que sí estaría leyendo un nivel de precios como si fuera un motor de reservas.',
    it: "La domanda è quanto costa un viaggio al giorno, che non è la domanda su quanto costa vivere in un paese e si tratta con la stessa fonte letta in un altro modo. Il paniere di un residente pesa su affitto ed energia, quello di un visitatore su ristoranti, alberghi e trasporti, e proprio queste tre categorie sono pubblicate separate, quindi la stima usa loro e non la cifra complessiva. Non può dare il prezzo di un albergo preciso né di un volo preciso, e uno strumento che lo pretendesse leggerebbe un livello dei prezzi come se fosse un motore di prenotazione.",
    pt: 'A pergunta é quanto custa uma viagem por dia, que não é a pergunta de quanto custa viver num país e responde-se com a mesma fonte lida de outra maneira. O cabaz de quem mora pesa na renda e na energia, o de quem visita pesa nos restaurantes, hotéis e transportes, e essas três categorias são publicadas em separado, por isso a estimativa usa-as e não o número global. Não consegue pôr preço a um hotel concreto nem a um voo concreto, e uma ferramenta que dissesse que sim estaria a ler um nível de preços como se fosse um motor de reservas.',
    nl: 'De vraag is wat een reis per dag kost, en dat is een andere vraag dan wat het kost om in een land te wonen, beantwoord met dezelfde bron anders gelezen. Het mandje van een bewoner weegt zwaar op huur en energie, dat van een bezoeker op restaurants, hotels en vervoer, en juist die drie categorieën worden apart gepubliceerd, dus de schatting rekent met hen en niet met het totaalcijfer. Een bepaald hotel of een bepaalde vlucht kan zij niet beprijzen, en een hulpmiddel dat dat beweerde zou een prijspeil lezen alsof het een boekingssysteem was.',
    pl: 'Pytanie brzmi, ile kosztuje podróż na dzień, a to nie jest pytanie o koszt życia w kraju i odpowiada się na nie tym samym źródłem, czytanym inaczej. Koszyk mieszkańca ciąży ku czynszowi i energii, koszyk odwiedzającego ku restauracjom, hotelom i transportowi, a właśnie te trzy kategorie publikowane są osobno, więc szacunek opiera się na nich, a nie na liczbie ogólnej. Nie wyceni konkretnego hotelu ani konkretnego lotu, a narzędzie, które twierdziłoby inaczej, czytałoby poziom cen tak, jakby był wyszukiwarką rezerwacji.',
    ja: '問いは、旅が一日いくらかかるかである。これは国に住む費用の問いとは別で、同じ出典を別の読み方で使って答える。住む人の買い物かごは家賃と光熱に重く、訪れる人の買い物かごは外食、宿泊、交通に重い。この三つの品目は別々に公表されているので、この計算は全体の数値ではなくそちらを使う。特定のホテルや特定の便の値段は出せない。出せると言う道具があれば、それは物価水準を予約サイトのように読んでいるだけである。',
  },
  'relocation-budget': {
    en: 'The question here is what the first months cost, which is not what a month costs once you have settled. The one off items dominate and most of them are outside any statistical series: a deposit, an agency fee, the gap between two rents, registration, a car, furniture for an empty flat. What the published data can do is anchor the recurring half, the basket and the pay, and what this page will not do is invent the one off half or present the two added together as though both were measured.',
    de: 'Die Frage ist, was die ersten Monate kosten, und das ist nicht, was ein Monat kostet, wenn man angekommen ist. Die einmaligen Posten überwiegen, und die meisten stehen in keiner statistischen Reihe: Kaution, Maklergebühr, die Lücke zwischen zwei Mieten, Anmeldung, ein Auto, Möbel für eine leere Wohnung. Was die veröffentlichten Daten leisten, ist die wiederkehrende Hälfte zu verankern, Warenkorb und Verdienst, und was diese Seite nicht tut, ist die einmalige Hälfte zu erfinden oder beide zusammenzuzählen, als wären sie beide gemessen.',
    fr: "La question est de savoir ce que coûtent les premiers mois, ce qui n'est pas ce que coûte un mois une fois installé. Les dépenses uniques dominent et la plupart ne figurent dans aucune série statistique : une caution, des frais d'agence, le chevauchement de deux loyers, l'inscription, une voiture, des meubles pour un appartement vide. Ce que les données publiées savent faire, c'est ancrer la moitié récurrente, le panier et le salaire, et ce que cette page ne fera pas, c'est inventer l'autre moitié ni additionner les deux comme si elles étaient toutes deux mesurées.",
    es: 'La pregunta es cuánto cuestan los primeros meses, que no es lo que cuesta un mes una vez instalado. Mandan los gastos de una sola vez y casi ninguno está en serie estadística alguna: una fianza, la comisión de la agencia, el solape de dos alquileres, el empadronamiento, un coche, muebles para un piso vacío. Lo que los datos publicados sí pueden hacer es anclar la mitad recurrente, la cesta y el sueldo, y lo que esta página no hará es inventarse la otra mitad ni sumar las dos como si ambas estuvieran medidas.',
    it: "La domanda è quanto costano i primi mesi, che non è quanto costa un mese una volta sistemati. Dominano le voci una tantum e quasi nessuna sta in una serie statistica: una caparra, la provvigione, la sovrapposizione di due affitti, la residenza, un'auto, i mobili per una casa vuota. Quello che i dati pubblicati sanno fare è ancorare la metà ricorrente, il paniere e la retribuzione, e quello che questa pagina non farà è inventare l'altra metà né sommare le due come se fossero entrambe misurate.",
    pt: 'A pergunta é quanto custam os primeiros meses, que não é o que custa um mês depois de instalado. Mandam as despesas de uma só vez e quase nenhuma está em série estatística nenhuma: uma caução, a comissão da agência, a sobreposição de duas rendas, o registo, um carro, mobília para uma casa vazia. O que os dados publicados conseguem fazer é ancorar a metade recorrente, o cabaz e o ordenado, e o que esta página não fará é inventar a outra metade nem somar as duas como se ambas fossem medidas.',
    nl: 'De vraag is wat de eerste maanden kosten, en dat is niet wat een maand kost als u eenmaal gesetteld bent. De eenmalige posten overheersen en de meeste staan in geen enkele statistische reeks: een borg, bemiddelingskosten, de overlap van twee huren, inschrijving, een auto, meubels voor een lege woning. Wat de gepubliceerde data wel kunnen, is de terugkerende helft verankeren, het mandje en het loon, en wat deze pagina niet doet, is de andere helft verzinnen of beide optellen alsof ze allebei gemeten waren.',
    pl: 'Pytanie brzmi, ile kosztują pierwsze miesiące, a to nie to samo co koszt miesiąca, gdy już się osiądzie. Przeważają wydatki jednorazowe, a większości z nich nie ma w żadnej serii statystycznej: kaucja, prowizja agencji, nakładanie się dwóch czynszów, meldunek, samochód, meble do pustego mieszkania. Opublikowane dane potrafią zakotwiczyć połowę powtarzalną, koszyk i wynagrodzenie, a czego ta strona nie zrobi, to wymyślić drugiej połowy ani dodać obu tak, jakby obie były zmierzone.',
    ja: '問いは最初の数か月がいくらかかるかであり、落ち着いたあとの一か月の費用とは別物である。効いてくるのは一度きりの出費で、その多くはどの統計にも載っていない。敷金、仲介手数料、家賃が二重に走る期間、住民登録、車、空の部屋に入れる家具。公表データにできるのは、繰り返し出ていく側、つまり買い物かごと賃金を固定することだけである。このページがしないのは、一度きりの側を作り出すことと、両方を足して二つとも測定済みであるかのように見せることである。',
  },
  'city-comparison': {
    en: 'The question here is how two places stand against each other across several measures at once rather than on one headline. That is the useful comparison and it is also where a tool most easily misleads, by lining up numbers that were collected differently and letting the layout imply they belong side by side. So each row says which measure it is, which year it describes and which institution published it, and a row that exists for one side and not the other stays visibly empty rather than being filled with the other side\'s figure.',
    de: 'Die Frage ist, wie zwei Orte über mehrere Kennzahlen hinweg zueinander stehen und nicht nur über eine Gesamtzahl. Das ist der nützliche Vergleich und zugleich die Stelle, an der ein Werkzeug am leichtesten in die Irre führt, indem es unterschiedlich erhobene Zahlen nebeneinanderstellt und das Layout suggerieren lässt, sie gehörten zusammen. Deshalb nennt jede Zeile ihre Kennzahl, ihr Jahr und die Institution dahinter, und eine Zeile, die es nur für eine Seite gibt, bleibt sichtbar leer, statt mit der Zahl der anderen Seite gefüllt zu werden.',
    fr: "La question est de savoir comment deux endroits se situent l'un par rapport à l'autre sur plusieurs mesures à la fois plutôt que sur un seul chiffre. C'est la comparaison utile et c'est aussi là qu'un outil trompe le plus facilement, en alignant des nombres collectés autrement et en laissant la mise en page suggérer qu'ils vont ensemble. Chaque ligne indique donc sa mesure, son année et l'institution qui l'a publiée, et une ligne qui n'existe que d'un côté reste visiblement vide plutôt que d'être remplie avec le chiffre de l'autre.",
    es: 'La pregunta es cómo quedan dos sitios uno frente al otro en varias medidas a la vez y no en una sola cifra. Esa es la comparación útil y es también donde una herramienta engaña con más facilidad, alineando números recogidos de distinta manera y dejando que la maquetación sugiera que van juntos. Por eso cada fila dice qué medida es, qué año describe y qué institución la publicó, y una fila que existe para un lado y no para el otro se queda visiblemente vacía en vez de rellenarse con la cifra del otro.',
    it: "La domanda è come stanno due posti l'uno rispetto all'altro su più misure insieme e non su una cifra sola. È il confronto utile ed è anche il punto in cui uno strumento inganna più facilmente, allineando numeri raccolti in modi diversi e lasciando che l'impaginazione suggerisca che stiano insieme. Per questo ogni riga dice quale misura è, quale anno descrive e quale istituzione l'ha pubblicata, e una riga che esiste per un lato e non per l'altro resta visibilmente vuota invece di essere riempita con la cifra dell'altro.",
    pt: 'A pergunta é como ficam dois sítios um face ao outro em várias medidas ao mesmo tempo e não numa só cifra. Essa é a comparação útil e é também onde uma ferramenta engana com mais facilidade, alinhando números recolhidos de maneiras diferentes e deixando o alinhamento sugerir que andam juntos. Por isso cada linha diz que medida é, que ano descreve e que instituição a publicou, e uma linha que existe para um lado e não para o outro fica visivelmente vazia em vez de ser preenchida com o valor do outro.',
    nl: 'De vraag is hoe twee plaatsen zich tot elkaar verhouden over meerdere maatstaven tegelijk en niet op één totaalcijfer. Dat is de nuttige vergelijking en het is ook waar een hulpmiddel het makkelijkst misleidt, door verschillend verzamelde getallen naast elkaar te zetten en de opmaak te laten suggereren dat ze bij elkaar horen. Daarom noemt elke rij haar maatstaf, haar jaar en de instelling erachter, en een rij die er voor de ene kant wel is en voor de andere niet blijft zichtbaar leeg in plaats van gevuld te worden met het cijfer van de andere.',
    pl: 'Pytanie brzmi, jak dwa miejsca wypadają wobec siebie na kilku miarach naraz, a nie na jednej liczbie ogólnej. To jest porównanie użyteczne i zarazem miejsce, w którym narzędzie najłatwiej wprowadza w błąd, ustawiając obok siebie liczby zbierane inaczej i pozwalając, by układ sugerował, że do siebie pasują. Dlatego każdy wiersz podaje swoją miarę, rok, którego dotyczy, i instytucję, która go opublikowała, a wiersz istniejący tylko po jednej stronie zostaje widocznie pusty, zamiast być wypełniony liczbą z drugiej strony.',
    ja: '問いは、一つの代表値ではなく複数の指標で二つの場所がどう並ぶかである。役に立つのはこちらの比較だが、道具が最も誤解を招きやすいのもここである。集め方の違う数字を並べ、体裁のせいで同じ土俵に見えてしまうからだ。だから各行には、どの指標か、どの年のものか、どの機関が公表したかを書く。片方にしかない行は、もう片方の数字で埋めず、空のまま見えるようにしておく。',
  },
};

export const toolCopy = (id, language) => (T[id] ? T[id][language] || null : null);
export const toolsCovered = () => Object.keys(T);
export function missingToolCopy(ids, languages) {
  const gaps = [];
  for (const id of ids) for (const l of languages) if (!toolCopy(id, l)) gaps.push(id + ' has no copy in ' + l);
  return gaps;
}
